### ISSUE TITLE
General Keyboard shortcuts

### ISSUE THREAD

**Issue by colelawrence** [silverwind/droppy#108]
General tree traversal and file operations via keyboard could be supported better.
**Directory**

`Up`, `Down` switch current entry (based on order)

> ```
> var nextEntryIndex = $(prevEntry).attr("order") + 1 or -1;
> $(".data-row[order='" + nextEntryIndex + "']").makeCurrent();
> ```

`Alt-Up` switch to parenting folder

`Enter` emulate clicking the entry

`contextmenu` on contextmenu button open the entry-menu (also for right clicking anyway) [event example](http://jsfiddle.net/MjRyL/)

**General**

`metaKey-Left` split views, current view moves left (or switch view spots)
`metaKey-Right` split views, current view moves right (or switch view spots)

`Alt-1` focus on view 0
`Alt-2` focus on view 1

**Comment by silverwind** [comment]
I'll probably switch over key binding to [mousetrap](https://github.com/ccampbell/mousetrap) so I don't have to remember keyCodes and to easier bind combo keys.

**Comment by silverwind** [comment]
mousetrap is in. I'll intend to add a few more useful bindings like arrow keys to navigate the directories, as well as arrow support in non-fullscreen media galleries.

**Comment by silverwind** [comment]
Closing off some old irrelevant issues.
