### ISSUE TITLE
Drag and drop TODOs

### ISSUE THREAD

**Issue by silverwind** [silverwind/droppy#109]
Here's two things about them I'd like to fix:
- When dropping a file from one view to another, there shouldn't be dropzones for each folder, but instead only a single one for the whole target view.
- Generally, d&d seems pretty laggy. I wonder if we process an unnecessary large amount of `mousemove` or something.

**Comment by 1tron1** [comment]
![image](https://cloud.githubusercontent.com/assets/6299790/23802632/e4734976-0581-11e7-8494-8b6d969062b0.png)


Is this a known issue with drag and dropping folders into each other?

**Comment by silverwind** [comment]
@1tron1 which browser are you using?

**Comment by 1tron1** [comment]
Chrome and FF.

**Comment by silverwind** [comment]
Hmm, I cannot reproduce and I'm really not sure what could cause the almost-black overlay you're seeing. Can you reproduce on [the demo site](https://droppy.silverwind.io)? Here's what I see when I drag a item:

<img width="1280" src="https://cloud.githubusercontent.com/assets/115237/23822304/df6e902e-064a-11e7-9586-a7169a999876.png">

Once I let go of the button, it shows the move/copy/view menu.
