### ISSUE TITLE
Limit watcher updates on directories undergoing writes

### ISSUE THREAD

**Issue by ZombieHippie** [silverwind/droppy#162]
When copying and pasting a folder the file size changes are constantly sent to you as the file operation is processed, I would expect the same would happen when uploading a folder.

**Comment by silverwind** [comment]
With the new watcher library, we get pretty nice file system events (including changed files):
````
2015-02-01 00:50:44 [DEBG] Watcher event: 'add' in /code
2015-02-01 00:50:46 [DEBG] Watcher event: 'unlink' in /code
2015-02-01 00:50:47 [DEBG] Watcher event: 'unlink' in /code
````
This really calls for differential updates to the client now :)
