### ISSUE TITLE
Short links/separate containers for sharing for folders

### ISSUE THREAD

**Issue by Poorchop** [silverwind/droppy#181]
Sometimes I want to share a number of files with family, and I think this could be made a little easier for the user. Right now, short links only seem like an option for individual files. If this could be expanded to include folders, it would be easier to copy/paste a link to send to someone else. I'm guessing I could just send a `https://example.com/?~~/folder/to/share` to someone so they can download the zip file, but a popup with a link to copy would save a little time.

Also, a "share" feature that creates kind of a separate user space would be ideal for sharing folders. I have friends and family who are completely technology illiterate and they still don't know how to double click to unzip a file, even if I draw pictures for them. If a sharing link is generated for the folder, then it could exist at its own separate link for securely sharing with anyone so that they can go through the folder at their leisure without modifying its contents or without being able to access anything outside of that area. This would be perfect for sharing large photo collections that my family could browse through right on droppy since it has a built in photo viewer.

One last thing - maybe clicking on the yellow icon in the popup when the short link is generated can automatically copy it to the clipboard.

**Comment by Poorchop** [comment]
I can't remember if the clipboard thing was being tracked in another issue but apparently [it's possible without flash now](https://github.com/zenorocha/clipboard.js).

**Comment by silverwind** [comment]
@Poorchop I'm already doing it without flash that since around a month :)

https://github.com/silverwind/droppy/blob/9332be76045581169c6e683fb2632e681988f0f2/client/client.js#L2608-L2615

**Comment by silverwind** [comment]
Closing off some old irrelevant issues.
