### ISSUE TITLE
Theming / Styling Documentation

### ISSUE THREAD

**Issue by colelawrence** [silverwind/droppy#183]
It would be nice to change styling based on different applications (colors, background-colors, svg fillcolors).

Providing documentation, or centralizing main colored classes in a single place would be beneficial.

I would really like to use droppy in a super boring, zero-anim, [elFinder-like](http://elfinder.org/) manner which, conceptually, may project a strong and stable interface.

**Comment by silverwind** [comment]
This would be such a good use case for [CSS Variables](http://caniuse.com/#feat=css-variables). Oh wait, Chrome dropped support for them :cry:.

**Comment by silverwind** [comment]
Closing off some old irrelevant issues.
