### ISSUE TITLE
Chromecast support

### ISSUE THREAD

**Issue by ZombieHippie** [silverwind/droppy#188]
Based on what I know about the Chromecast, it does not look like we would be straining ourselves to make droppy compatible with it.

I think all we would need is to be able to open a video stream with a single request as in a REST API.

**Comment by silverwind** [comment]
Probably not going to do this in the near future, sorry.

**Comment by ZombieHippie** [comment]
Darn. c:

**Comment by silverwind** [comment]
What can be done is something like a share-link, but for mp4 media, with unauthenticated access of course. I'm sure there's a way to put a URL into a streaming device like Chromecast :)

**Comment by silverwind** [comment]
Or maybe the current share links even work, I think devices should probably ignore a download header when accessing a stream :)
