### ISSUE TITLE
Detached frontend

### ISSUE THREAD

**Issue by colelawrence** [silverwind/droppy#191]
The second part of #171 would be the ability to actually use the file browsing part of droppy for browser application and include `droppy.onFileOpen`, `droppy.onFileChanged` events to the browser for the other side to handle. Then obviously `droppy.setFileContents(String path, String/ArrayBuffer data, Function callback)`

This function relies particularly on permissions and authentication efforts we have planned. Perms #129, Auth #170, REST #186

**Comment by silverwind** [comment]
Closing off some old irrelevant issues.
