### ISSUE TITLE
Better templating system

### ISSUE THREAD

**Issue by ZombieHippie** [silverwind/droppy#192]
If we end up doing a lot more with templating, in the future I'd really like to change to [`jade`](https://github.com/visionmedia/jade) because it is nicer to work with in general, and I've been using it a lot for client side templating  recently so I have a lot of knowledge about implementation methods that I did not have before when we started with doTjs

**Comment by silverwind** [comment]
Recently switched to Handlebars while also moving all JS out of the template. Much cleaner now.
