### ISSUE TITLE
iOS drag and drop, on-demand CM plugins

### ISSUE THREAD

**Issue by mdonges** [silverwind/droppy#203]
So, this is not an issue but more a feature request.
I looked at your code and I like it. Started to youe droppy heavily and would like to get to know you...
I use my iPad heavily too, but there is still many shortcomings. I guess you are able to quickly overcome many of them in few extra effort ;) 

One is copy and paste. A rally nasty thing not at all working on iPad.
Do you know this work?
https://github.com/schanzer/CodeMirror/blob/master/demo/iOS.html

Droppy is wonderful on mobile browsers. What an enhancement these tiny features would bring to droppy :)

I also love tern server, but the CM tern addon is not really perfect for the droppy Ressource management. I stopped trying it, when I got "tern.Server" not defined. This happens due to your interesting way of script concatenation...

Please take my highest respect for your wonderful work.
I hope my 2 cents might inspire you additionally...

Donges@cquadrat.com

**Comment by silverwind** [comment]
I'm not interested in adding IOS specificy hacks at this point, and will support Firefox and Chrome on Android, so really not much to do here. CM plugins are on my TODO list though.
