### ISSUE TITLE
Symlink support

### ISSUE THREAD

**Issue by silverwind** [silverwind/droppy#225]
Just noticed while I wanted to symlink a logfile into droppy, that these are apparently not detected as files at all, being invisible to the frontend.

**Comment by silverwind** [comment]
Turns out it was just a permission problem and the `stat()` call failed. This pointed out another uncaught exception, which I'll fix.

**Comment by jfaryad** [comment]
What kind of permission problem was this, please? I'm getting also a stat error with symlink files but I haven't figured a way around it. And this issue, although almost 2 years old, is the only one that sounds like it might be the same problem, which would suggest it's me doing something wrong.

Steps to reproduce:

(Note: the following is executed as a user with UID/GID 1000/1000)

mkdir ~/droppytest && \
echo "hello" > ~/hello.txt && \
cd ~/droppytest && \
ln -s ~/hello.txt ~/droppytest/hello.txt

docker run --name droppy -p 8080:8989 --env UID=1000 --env GID=1000 -v ~/droppytest:/files  silverwind/droppy

`
           .:.
    :::  .:::::.   droppy 6.8.11 running on node 9.1.0
  ..:::..  :::     config at /config
   ':::'   :::     files at /files
     '

2017-11-22 09:43:35 [INFO] Loading resources ...
2017-11-22 09:43:35 [INFO] Loading resources done
2017-11-22 09:43:35 [INFO] Listening on http://127.0.0.1:8989
2017-11-22 09:43:35 [INFO] Listening on http://172.17.0.1:8989
2017-11-22 09:43:35 [INFO] Listening on http://[::1]:8989
2017-11-22 09:43:35 [INFO] Listening on http://[fe80::42:acff:fe11:1]:8989
2017-11-22 09:43:35 [INFO] Caching files ...
2017-11-22 09:43:35 [ERROR] ENOENT: no such file or directory, stat '/files/hello.txt'
    at Object.fs.statSync (fs.js:968:11)
    at Object.walker.walkSync (/droppy/server/walker.js:63:27)
    at /droppy/server/filetree.js:100:24
    at /droppy/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:167:5)
2017-11-22 09:43:35 [INFO] Caching files done
2017-11-22 09:43:35 [INFO] Ready for requests!
`

**Comment by silverwind** [comment]
This is more or less a limitation of Docker. Check out the symlink inside the container:

````
$ docker exec -it droppy sh
/ # ls /files/ -la
total 4
drwxr-xr-x    3 droppy   droppy          96 Nov 22 17:33 .
drwxr-xr-x    1 root     root          4096 Nov 22 17:35 ..
lrwxr-xr-x    1 root     root            27 Nov 22 17:33 hello.txt -> /Users/silverwind/hello.txt
````

As a symlink is basically just a text file containing a path, it is pointing to the path on the host machine which isn't valid inside the container. You could attempt to workaround by re-creating the host machine's paths inside the container, also see https://stackoverflow.com/questions/38485607/mount-host-directory-with-a-symbolic-link-inside-in-docker-container.

**Comment by jfaryad** [comment]
I see, of course. Thank you!
