### ISSUE TITLE
Server response prediction

### ISSUE THREAD

**Issue by silverwind** [silverwind/droppy#233]
There's a possibilty to predict certain responses from the server, reducing perceived latency to zero. I could think of these off the head:
- delete an entry
- create new entries
- copy an entry into the current directory
- uploading

All these actions can be immediately updated in the client. The server will still send its update after a roundtrip + however long the file system action takes, so it's still getting synced afterwards (but shouldn't change).

**Comment by ZombieHippie** [comment]
Good idea, sounds like this would be fun to design.

**Comment by silverwind** [comment]
Yes, I think I will first try redesign how the file/folder data from the server gets updated. Right now this is hugely inefficient by feeding the JSON into the template and then re-rendering the whole thing.

I think some React-like approach would be best. Only the differences need to be rendered. Same functions that add/remove things could then be re-used for prediction.

**Comment by silverwind** [comment]
In-memory fs is done, and seems to perform great so far.

**Comment by silverwind** [comment]
Closing off some old irrelevant issues.
