### ISSUE TITLE
Use AMD

### ISSUE THREAD

**Issue by silverwind** [silverwind/droppy#238]
I'm looking to move everything over to a more modular aproach. CodeMirror, video.js and Draggabilly support RequireJS for lazy-loading, and I can finally start to split up the huge `client.js`.

The long term would be to transition to ES6 modules, but that's at least a year off until browser support.

**Comment by silverwind** [comment]
I've decided against this for the time being.

**Comment by ZombieHippie** [comment]
I've been playing with Webpack recently, and it supports bundling several different modularization libraries, and ES6. It might have a good fit in the droppy project

**Comment by silverwind** [comment]
Yes, it look suitable with my requirements (primarily async on-demand loading), but my ultimate decision against a module system was the added overhead from the module loaders, which was at least 20kB minified for the ones that support async loading, last I checked. Do you have a estimate on how much Webpack would add?

**Comment by silverwind** [comment]
I'm probably not grasping how Webpack works yet, so I might be wrong about added overhead on the client. Got some reading up to do. [This](https://gist.github.com/substack/68f8d502be42d5cd4942) looks interesting.

**Comment by ZombieHippie** [comment]
I don't have a good estimate, but webpack tends to become extremely tiny after proper deadcode removal and minification. We are just now separating our code out into separate modules on the project I'm working on, so after that I can contribute the knowledge I will have ascertained.

I believe Webpack reduces module loading code in production mode to bear minimums.
