### ISSUE TITLE
No option to add folder

### ISSUE THREAD

**Issue by Poorchop** [silverwind/droppy#241]
The option to upload a folder to the current directory is grayed out for me. I did a recent reinstall of droppy after recently losing everything on my previous server, but last I remember, it was possible for me to upload a folder before.

**Comment by silverwind** [comment]
Only Webkit-based browser support the necessary API, which one are you using?

**Comment by Poorchop** [comment]
Well that explains it. I'm using Firefox.

**Comment by silverwind** [comment]
In case you're interested, here's the relevant Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=876480
