### ISSUE TITLE
Improve startup time

### ISSUE THREAD

**Issue by silverwind** [silverwind/droppy#242]
A huge chunk of the startup time is spent in `server/lib/resources.js` to minify frontend resources. I think this part can be moved to a npm postinstall script to run once per install/update, or possibly on-demand through a cli-option if needed.

**Comment by Poorchop** [comment]
>I think this part can be moved to a npm postinstall script to run once per install/update

I would welcome that change. Droppy now takes seven minutes to start up on my server, whereas earlier versions would take maybe a minute or less if I'm remembering correctly.

**Comment by silverwind** [comment]
This will have another benefit of being able to remove the `uncaughtException` hook and do a clean and fast restart on crash. Might want to get persistent logging in first before doing so though.

FYI: The majority of time is spent minifying CodeMirror.

**Comment by silverwind** [comment]
Added some rudimentary caching for client resources. This should eliminate most of the startup time on restarts. If client code updates, it will recompile once.

Still have to look into running this on post-install to eliminate server downtime during updates.

**Comment by silverwind** [comment]
This is fixed completely. Client files are precompiled and published under `dist/cache.json` now.
