### ISSUE TITLE
Can't launch 2.1.19

### ISSUE THREAD

**Issue by Poorchop** [silverwind/droppy#243]
I'm getting this error after updating droppy and trying to launch:

```
2015-05-15 23:11:03 [ERROR] =============== Uncaught exception! ===============
2015-05-15 23:11:04 [ERROR] TypeError: Cannot read property 'users' of undefined
    at Object.db.get (/usr/lib/node_modules/droppy/server/lib/db.js:61:20)
    at async.series.resources.init.cache (/usr/lib/node_modules/droppy/server/server.js:54:39)
    at /usr/lib/node_modules/droppy/node_modules/async/lib/async.js:610:21
    at /usr/lib/node_modules/droppy/node_modules/async/lib/async.js:249:17
    at iterate (/usr/lib/node_modules/droppy/node_modules/async/lib/async.js:149:13)
    at /usr/lib/node_modules/droppy/node_modules/async/lib/async.js:160:25
    at /usr/lib/node_modules/droppy/node_modules/async/lib/async.js:251:21
    at /usr/lib/node_modules/droppy/node_modules/async/lib/async.js:615:34
    at /usr/lib/node_modules/droppy/server/lib/db.js:33:32
    at evalmachine.<anonymous>:272:14
```

I ran `npm update -g` rather than just specifically updating droppy, and it looked like the process failed when it got to updating droppy. I uninstalled droppy and did a fresh re-install with no error messages from npm, but now I'm getting this when starting droppy.

**Comment by silverwind** [comment]
That shouldn't happen. Does `~/.droppy/config/db.json` exist and are it's content valid json?

**Comment by Poorchop** [comment]
db.json exists but it wasn't valid json. I have no idea how that happened because I never touched that file. However, I did do a system update and it seems to have broken at least a few things so far, so maybe db.json somehow got messed up in that process.

I deleted db.json and droppy started up without any issues.

**Comment by silverwind** [comment]
Still can't explain it happening. Invalid JSON is caught [here](https://github.com/silverwind/droppy/blob/fa41c382ffaefed55bc260493c4429e487698edd/server/lib/db.js#L33) and should have given you a JSON parse error. I double checked the db code and it seems fine. What *did* it contain?

**Comment by Poorchop** [comment]
Looks like the salt is randomly generated when a new user is added but I'm removing the private stuff anyway:

```json
{
  "users": {
    "[me]": {
      "hash": "[hash]",
      "privileged": true
    }
  },
  "sessions": {},
  "sharelinks": {}
}[random string of letters and numbers]": {
      "privileged": true,
      "lastSeen": [numbers]
    }
  },
  "sharelinks": {}
}%
```

In addition to the missing curly brackets, that unmatched `"` was actually in there as well.

I also ran 2.1.19 just fine prior to rebooting. I was testing to see if it would still work despite npm throwing that error message at me. I think this is related to my system and not to droppy because the reboot broke other things as well. However, I'm not sure why I didn't get the invalid JSON error.

**Comment by silverwind** [comment]
Interesting. i still think something inside droppy caused that corruption. I'll research.
