### ISSUE TITLE
"Add User" on the web interface does not work

### ISSUE THREAD

**Issue by jzjsuper** [silverwind/droppy#246]
I clicked `Add User` in `Prefs` on the webinterface, and nothing happened. No log in the server side, too. (I've set `logLevel` to `3`.)

Version:  droppy 2.3.18 running on nodejs 0.12.7
OS:  Ubuntu 14.04.2 LTS (in vagrant, provider is virtualbox 4.3.30)
Browser: Google Chrome 43.0.2357.134

**Comment by silverwind** [comment]
Thanks for reporting, I think I accidentially broke it when changing the template language recently. :blush:

**Comment by silverwind** [comment]
Fixed in 2.3.19
