### ISSUE TITLE
Droppy is not working on safari

### ISSUE THREAD

**Issue by txchen** [silverwind/droppy#248]
The web UI cannot render correctly. Tested on iOS and OSX.

**Comment by silverwind** [comment]
Got a screenshot? Looks fine here on OS X:

![screen shot 2015-09-21 at 7 55 31 pm](https://cloud.githubusercontent.com/assets/115237/10000158/c4416b2a-609a-11e5-9238-b0bb07c68326.png)

**Comment by txchen** [comment]
It is all black

![image](https://cloud.githubusercontent.com/assets/713074/10000459/0db35b3c-6051-11e5-9ba8-00a028d88373.png)

**Comment by silverwind** [comment]
Just guessing: Are you correctly proxying WebSockets through your nginx? 

```nginx
    proxy_pass http://backend;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
```

https://github.com/silverwind/droppy/wiki/Nginx-reverse-proxy
http://nginx.org/en/docs/http/websocket.html

**Comment by txchen** [comment]
I opened dev tools and found this:

![image](https://cloud.githubusercontent.com/assets/713074/10000527/93b86b78-6051-11e5-87c3-10f9c422d3a5.png)


My setup:

I use nginx and forward to upstream droppy instance, in nginx, I use basic auth and I disabled auth in droppy.
Chrome and Firefox works well, safari cannot connect to ws

**Comment by txchen** [comment]
Oh Just saw your reply, I will have a try now.

**Comment by txchen** [comment]
My nginx setting (partial):

```
upstream droppy {
  server  127.0.0.1:9999;
}

location / {
    auth_basic "Restricted";
    auth_basic_user_file /etc/nginx/droppypasswd;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Real-Port $remote_port;
    proxy_set_header Host $http_host;
    proxy_pass http://droppy;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    add_header Strict-Transport-Security "max-age=31536000";
  }
```

**Comment by silverwind** [comment]
Hmm, that's pretty strange. Does the [http://droppy.silverwind.io](demo) work? What Safari version?

**Comment by silverwind** [comment]
Also, try https://www.websocket.org/echo.html using secure WebSocket.

**Comment by silverwind** [comment]
Oh, and for an explanation on the 401 response on the WebSocket request: This response is given when no cookie is sent.

Maybe you're blocking cookies, or something else is making the cookie go missing. I think I'll fix that by removing cookie usage when in public mode, they're not really necessary unless authentication is enabled.

**Comment by txchen** [comment]
Thanks a lot for your reply! @silverwind 

My browser supports websocket, and seems demo does not work well.

![image](https://cloud.githubusercontent.com/assets/713074/10002589/f0c3ed96-605c-11e5-9a59-345cc77987fd.png)

The menu is not rendered, and when I click the folder, it becomes black.

![image](https://cloud.githubusercontent.com/assets/713074/10002602/042bb396-605d-11e5-8a72-9061bb6cf08e.png)

**Comment by txchen** [comment]
Safari Version 8.0.8 (10600.8.9)

**Comment by txchen** [comment]
And I don't think my settings are blocking cookies, as far as I know.

On the other hand, chrome and firefox have no issues.

**Comment by silverwind** [comment]
That rendering looks like some oddity of Safari 8. I'm on Safari 9 already, so I can't really fix that without a browser to test on I'm afraid. As for cookies, make sure it's at least set to this:

![screen shot 2015-09-21 at 9 36 54 pm](https://cloud.githubusercontent.com/assets/115237/10002694/eff3b8b4-60a8-11e5-9555-74737a00af06.png)

You could also try to set 'Always allow', but it shouldn't change anything in theory.

**Comment by txchen** [comment]
Tried 'always allow', still same issue.

**Comment by silverwind** [comment]
Luckily, I have a test page for this exact issue. Could you post the content of [this site](http://wstest.silverwind.io/)?

**Comment by txchen** [comment]
Sure, my safari:

```
HTTP headers received

{ host: 'wstest.silverwind.io',
  connection: 'upgrade',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
  'accept-language': 'en-us',
  'accept-encoding': 'gzip, deflate',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9' }
WebSocket headers received

{ host: 'wstest.silverwind.io',
  upgrade: 'websocket',
  connection: 'upgrade',
  origin: 'http://wstest.silverwind.io',
  cookie: 'some=value',
  pragma: 'no-cache',
  'cache-control': 'no-cache',
  'sec-websocket-key': '733l+YcTyY5Rfm6DwSDvwg==',
  'sec-websocket-version': '13',
  'sec-websocket-extensions': 'x-webkit-deflate-frame',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9' }
```

**Comment by txchen** [comment]
From the nginx log. I see those 401 for ws requests from safari.

So I guess it is blocked by nginx's basicauth check, because the browser is not sending the authorization header. 

Not sure if this is a browser bug or client code can workaround this.

**Comment by txchen** [comment]
Well, now I think this is a safari issue because it is not passing credential in wss request.

Is wss a must from droppy, can this be turned off?

**Comment by silverwind** [comment]
Ah, so the 401 is from nginx instead of droppy, that explains it. Other browser are probably sending basic auth data on the Websocket Update request, while Safari likely doesn't. I'll read up more/test this, but sounds like a browser bug to me.

> Is wss a must from droppy, can this be turned off?

When the server is on https, it's forced to be wss.

**Comment by txchen** [comment]
Actually I mean: does droppy have a non-websocket mode? I that mode, it does polling to get information from server?

**Comment by silverwind** [comment]
Ah, no. Unfortunately WebSocket is a must right now, but I'll think about adding a polling fallback.

**Comment by txchen** [comment]
Thanks a lot for your support! Sorry for the false alarm. I am closing this and will try to use droppy's account system instead.

Thanks again!

**Comment by silverwind** [comment]
No problem! I just verified the issue is present in Safari 9 too, so I guess it's bug report time :)

**Comment by raybellis** [comment]
https://bugs.webkit.org/show_bug.cgi?id=80362

**Comment by silverwind** [comment]
@raybellis I do not see any issues regardin websocket authentication on Safari 12.0, what are you exactly experiencing? The only websocket-related bug in Safari that I'm aware of is that it won't work with self-signed SSL certificates.

**Comment by raybellis** [comment]
I'm not using droppy, but found this github issue when searching for related help.    If you have a websocket and http on the same domain and port, Safari doesn't pass the credentials used for the HTTP request when subsequently talking to the websocket, so the proxy always returns 401.

**Comment by silverwind** [comment]
Interesting, thanks. Maybe I'll switch to in-line authentication on the Websocket to avoid it.
