### ISSUE TITLE
 Error: listen EAFNOSUPPORT  

### ISSUE THREAD

**Issue by simpleuser99** [silverwind/droppy#249]
Hello
I have the next issue:

```
droppy start
     __
  --|  |---- ----- ----- ----- -- --
 |  _  |   _|  _  |  _  |  _  |  |  |
 |_____|__| |_____|   __|   __|___  |
                  |__|  |__|  |_____|

 droppy 3.5.3 running on node 0.10.36
 config at /root/.droppy
 files at /root/.droppy/files

2015-11-06 17:54:55 [INFO] Loading and minifying resources ...
2015-11-06 17:54:55 [INFO] Listening on http://10.13.1.14:8989
2015-11-06 17:54:55 [ERROR] Error: listen EAFNOSUPPORT
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:442:13)
[ERROR] Error: listen EAFNOSUPPORT
```

How can I fix it?

**Comment by silverwind** [comment]
Could I get some more detail of the IP configuration on your maching? Maybe post or mail me the output of `ip addr` or `ifconfig`. Is IPv4 perhaps disabled?

**Comment by simpleuser99** [comment]
`ifconfig
eth0      Link encap:Ethernet  HWaddr 00:50:56:9B:20:07
          inet addr:10.13.1.14  Bcast:10.13.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:76573 errors:0 dropped:0 overruns:0 frame:0
          TX packets:81254 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:104529807 (99.6 MiB)  TX bytes:16727394 (15.9 MiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:276 errors:0 dropped:0 overruns:0 frame:0
          TX packets:276 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:21438 (20.9 KiB)  TX bytes:21438 (20.9 KiB)`

` cat /etc/redhat-release
CentOS release 6.7 (Final)`

**Comment by silverwind** [comment]
Looks like it's related to the missing IPv6. I'll test in a VM.

**Comment by simpleuser99** [comment]
Ok. I am looking forward to the results

**Comment by silverwind** [comment]
While I couldn't reproduce your exact error, even when disabling IPv6, I now handle such listening errors gracefully and it will start up if at least one listening socket is present (while still printingt the errors, which you can fix through `droppy config`.

Relevant commits:

- https://github.com/silverwind/droppy/commit/d0c28f6106980731494cdafbb6d5eecf93d73d36
- https://github.com/silverwind/droppy/commit/a4dc3cc5d0b37335e3f3de2065bc2554cfaa43da

Thanks for reporting!

**Comment by simpleuser99** [comment]
I try to update and i have next error

make: Entering directory `/home/admin7/fsapp/droppy_new/droppy/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:
../node_modules/nan/nan.h:328: ошибка: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
make: *** [Release/obj.target/validation/src/validation.o] Ошибка 1
make: Leaving directory `/home/admin7/fsapp/droppy_new/droppy/node_modules/ws/node_modules/utf-8-validate/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-573.7.1.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/admin7/fsapp/droppy_new/droppy/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm http GET https://registry.npmjs.org/streamsearch/0.1.2
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/inherits

> bufferutil@1.2.1 install /home/admin7/fsapp/droppy_new/droppy/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/home/admin7/fsapp/droppy_new/droppy/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
npm http 304 https://registry.npmjs.org/streamsearch/0.1.2
In file included from ../src/bufferutil.cc:16:
../node_modules/nan/nan.h:328: ошибка: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Ошибка 1
make: Leaving directory `/home/admin7/fsapp/droppy_new/droppy/node_modules/ws/node_modules/bufferutil/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-573.7.1.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/admin7/fsapp/droppy_new/droppy/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.2.1

**Comment by silverwind** [comment]
This looks to be caused by the patched version of node which CentOS uses. I recommend using a nodesource version of node, ideally 0.12 or above: 

https://github.com/nodesource/distributions#installation-instructions-1

And then do a clean install.`
