### ISSUE TITLE
Read-only mode

### ISSUE THREAD

**Issue by ctlaltdefeat** [silverwind/droppy#250]
First of all, great job on this project.
Browsing through the configuration, I'm not quite certain if it's possible to allow read-only mode, whether globally or per-user. 
Is it possible, and if so, how?

**Comment by silverwind** [comment]
Not possible yet, but it's a good suggestion. I'll keep it no the radar.

**Comment by ctlaltdefeat** [comment]
I think that's a good idea, if it happens I can see it being a good alternative to https://github.com/lrsjng/h5ai

**Comment by ctlaltdefeat** [comment]
Have you gotten around to working on this by any chance?

**Comment by silverwind** [comment]
Not yet, but it's pretty high on my list, along with searching.

**Comment by silverwind** [comment]
Read-only mode is now available in 5.1.0. Set `readOnly: true` in your config to try it out!

The UI in that could certainly be improved, but I have to templatize a few HTML files first for that, which I'll do later.
