### ISSUE TITLE
Preferences for non-priviledged users

### ISSUE THREAD

**Issue by aranega** [silverwind/droppy#251]
Opening preferences window for non-priviledged users results in a direct window refresh and the preference windows is closed.

The issue seems to be here: https://github.com/silverwind/droppy/blob/master/client/client.js#L1778 
Replacing 

    if (Object.keys(userlist).length === 0) return location.reload(true);

by

    if (Object.keys(userlist).length === 0) return;

fixes the issue.

**Comment by silverwind** [comment]
Thanks, fixed. The reload is actually there for the case when the last user is deleted, so one can create a new one on the login page. I'll push a new version shortly.

**Comment by aranega** [comment]
Thanks a lot. 
Also, forgot to tell you in the first post, but droppy really rocks!

**Comment by silverwind** [comment]
Thank you :heart:
