### ISSUE TITLE
Docker image and UID/GID

### ISSUE THREAD

**Issue by gissehel** [silverwind/droppy#253]
The current docker image is great to handle folders dedicated to droppy (ie: when you first run droppy, you've got no files, and you'll only be access to the files through droppy).

But it's not perfect if you want to use a file folder that's already used in an other context, as the droppy process use UID/GID 0/0. All files will be created as root, and it may be a problem.

Solution: I write this script https://gist.github.com/gissehel/b0ce1aafed2c7f0087e8 that can be used as startup script (as a CMD command in the Dockerfile) that use env var UID / GID to use the uid/gid of the process.

I also put the config files in separate folder in order to be able either to mount /droppy-data or to mount /droppy-data/config on one volume, and /droppy-data/files on another (important if /droppy-data/files should point to an existing volume on the host)

**Comment by gissehel** [comment]
This script can be used with existing docker image by putting it on the host (with +x mode) and starting:

```sh
docker \
    run \
    --detach \
    --env UID=1004 \
    --env GID=1007 \
    --hostname droppy \
    --volume "${PATH_TO_CONFIG}:/config:rw" \
    --volume "${PATH_TO_FILES}:/files:rw" \
    --volume "${PATH_TO_SCRIPT}/start.sh:/start.sh:ro" \
    --name droppy \
    silverwind/droppy \
    /start.sh
```

**Comment by silverwind** [comment]
Interesting, I haven't really thought about permissions in regards to Docker yet.

> the droppy process use UID/GID 0/0. All files will be created as root, and it may be a problem.

You are talking about permissions inside the container, right? What kind of problems would root-owned files inside a container create? Security-related?

I'm thinking about adding `--pid`and `--gid` options so priviledges can be dropped at runtime, if that helps.

Oh, and splitting config and files into two seperate directories inside the container is something I'm planning to do.

**Comment by gissehel** [comment]
I'm talking about permissions (uid/gid) of a host's directory that would be mounted in the container.

Permissions of a volume are shared by the host and the container, so I'm talking about permission (uid/gid) inside AND outside the container.

If the "files" volume is only used within the container, this may not be a problem, 
The problem occurs if the files volume if already used elsewhere, with non null uid/gid.

Example:
- I've got a directory with code sources in /home/user/dev/project
- The files in that directory are sources, so text files.
- The files in that directory have uid / gid of the user "user" (let say uid 1007, gid 1002)
- I would like to use droppy to "manage" those files because being able to copy/download/upload/move/edit the files threw the web from time to time is awesome. 
- In the other hand, the main usage of that folder wouldn't be droppy, but being a source folder for development purpose within a home directory.

In that context, having every uid/gid permission changed to 0/0 (root/root) when editing a file is a problem.

**Comment by silverwind** [comment]
I think adding such a "wrapper" script as a ENTRYPOINT (in addition to CMD) might be the way to go to support additional arguments like `--uid` and `--gid`. One thing I'd like to make sure is that signals sent to the docker process will still reach the droppy process.

If you feel up to that task, feel free to send a pull request, otherwise, I'll get to it eventually. Still got a few things to learn regarding Docker :)

**Comment by gissehel** [comment]
Can you give an example of "signal" sending, how and why you're sending it ?

(I know how to send signals to processes, but I don't see in what use case you would send a signal to the "entrypoint" of the  docker container hosting droppy instead of sending it directly to the droppy process)

**Comment by silverwind** [comment]
> Can you give an example of "signal" sending, how and why you're sending it ?

SIGINT for example. Before https://github.com/silverwind/droppy/commit/97c1e55c5815c8a3d8ea1ab94ae357fc881e5f0c#diff-3254677a7917c6c01f55212f86c57fbfL23, the CMD in shell form which for some reason resulted in CTRL-C not working, for example when I want to stop a container attached to the terminal.

I've been reading up on wrapper scripts lately and came upon [this post](https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/#asimpleinitsystem) which suggest trapping signals in bash, but that seems like a hack. Not sure if this even applies to ENTRYPOINT scripts, but I'd at least make sure that [SIGINT, SIGTERM and SIGQUIT](https://github.com/silverwind/droppy/blob/4c24254f9e3a3879ccfd3c14ed15acf56efa28b6/server/server.js#L1088-L1090) make it through to the application.

**Comment by gissehel** [comment]
First, to fully address the problem of "the init process" described by your link on the post, the only clean way I know is to use a proper init process (a process that can handle "adopting" sub processes to be their parent).

The most common way is to use phusion/baseimage that use my_init (horrible name but does the job) as PID 1.

Here, the problem is much more simple. You need to have droppy lauched as PID 1 to be able to receive messages (SIGINT from console/SIGTERM from docker stop), and you need to have it lauched by a shell script to take care of UID/GID and even some folder things lauched as cmd/entrypoint thus as PID 1.

Looks like incopatible, except if there was a way to "replace" the shell process by a command.
And that's exactly what "exec" is for (while I knew it, it took me quite some time to realize this, while I has every bits of the answers in my head).

And yes, it works.

I tested it, by just adding  "exec" twice on the cmd line:

     /bin/su -m -s "/bin/sh" -c 'node droppy.js start -f /droppy-data/files --configdir /droppy-data/config' xuser

become:

     exec /bin/su -m -s "/bin/sh" -c 'exec node droppy.js start -f /droppy-data/files --configdir /droppy-data/config' xuser

Ctrl-C Stop the droppy process, and "docker exec droppy ps auxw" shows that droppy is PID 1.

I'll try to provide a pull request.

**Comment by silverwind** [comment]
Fixed in https://github.com/silverwind/droppy/commit/e617e8e05b0f4974af188d53945729c69395b8d9.
