### ISSUE TITLE
Execution Issue

### ISSUE THREAD

**Issue by James-Gallagher** [silverwind/droppy#258]
James@TestVPS5:/srv/droppy/config$ sudo droppy start --configdir /srv/droppy/config --filesdir /srv/droppy/files
           .:.        __                              
    :::  .:::::.   --|  |---- ----- ----- ----- -- -- 
  ..:::..  :::    |  _  |   _|  _  |  _  |  _  |  |  |
   ':::'   :::    |_____|__| |_____|   __|   __|___  |
     '                             |__|  |__|  |_____|

 droppy 4.2.3 running on node 4.2.6
 config at /srv/droppy/config
 files at /srv/droppy/files

2016-05-27 06:20:09 [INFO] Loading resources ...
2016-05-27 06:20:09 [INFO] Loading resources done
2016-05-27 06:20:09 [INFO] Listening on http://0.0.0.0
2016-05-27 06:20:09 [INFO] Failed to bind to :::80. Address already in use.
2016-05-27 06:20:09 [INFO] Caching files ...
2016-05-27 06:20:09 [INFO] Caching files done
2016-05-27 06:20:09 [INFO] Ready for requests!

I can't see what is wrong, port 80 is open and also not being used by any other application, this issue happens on any port I choose. Please help.

**Comment by silverwind** [comment]
The issue seems that port 80 on IPv6 looks to be bound. I think it correctly binds to IPv4 from the output above. You should be able to see what's listening through `sudo ss -tnlp`. If you only want IPv4, you could remove the `"::"` host from `/srv/droppy/config/config.json`, like:

````json
"listeners": [
  {
    "host": "0.0.0.0",
    "port": 80,
    "protocol": "http"
  }
],
````

**Comment by Augustus78** [comment]
I get the same error. I have tried many ports, everytime the same message:
2016-06-07 12:12:29 [INFO] Listening on http://127.0.0.1:8989
2016-06-07 12:12:29 [INFO] Failed to bind to :::8989. Address already in use.
BUT it works. So the message is simple sometimes wrong. I am not a Node developer, but maybe somebody can fix it.

droppy 4.2.5
node 4.4.5

**Comment by silverwind** [comment]
I see these errors too in Docker containers that don't have IPv6 set up. I guess some environments now map `0.0.0.0` (all interfaces) to IPv6 interfaces too, making the subsequent bind on `::` (all IPv6 interfaces) unnecessary and the error irrelevant. I'll think about hiding it if `0.0.0.0` worked.

**Comment by silverwind** [comment]
As a quick fix, `"host": "0.0.0.0"` in your config.json should work.

**Comment by Augustus78** [comment]
Thank you for your reply. You give me a hint that fixed the "problem". I am new to IPv6 and thus I disable IPv6 on all of my systems to avoid IPv4 firewall bypasses. The default config is
"host": [
        "0.0.0.0"
       , "::"
      ],
and I did not know that :: is for IPv6... I remove "::" and now no error occurs. 

Sorry, the error message was correct, because it was not posible to bind to :: if IPv6 is disabled.

**Comment by silverwind** [comment]
I saw the error happening on a IPv6 enabled machine too. I think it might have something to do how Node.js binds/resolves the underlying OS sockets. Filed https://github.com/nodejs/node/issues/7200.

**Comment by silverwind** [comment]
Applied a workaround in https://github.com/silverwind/droppy/commit/110e3de3cd4c777acfdab6bf218d43fdaf009aec, this misleading error should be gone with that!
