### ISSUE TITLE
Config "maxFileSize" work not as expected

### ISSUE THREAD

**Issue by Augustus78** [silverwind/droppy#259]
I tried the maxFileSize setting. It worked but not as I expected. It is possible to upload files of any size, but the file is simply truncated to maxFileSize. This way the user do not get any warning and it creates corrupted files. Maybe there is no simple way to implement this via browser upload. This is only a report of the behavior.

**Comment by silverwind** [comment]
Thanks for reporting. I wasn't aware that my multipart libary was truncating. I implemented a server-side check with an error on the client. I might to an additional check on the client later so no upload is attempted, but my file parsing library would need an extension first, so putting it off for now :)
