### ISSUE TITLE
[Might be me] Downloads on mobile (Oneplus One Chrome) not finishing.

### ISSUE THREAD

**Issue by JustRamon** [silverwind/droppy#261]
For some reason when I download files from my droppy client on my smartphone, it just doesn't finish. It also doesn't give any percentage in the download notification, it just keeps doing it's "getting ready to download" animation. 

Now this might be me, but I have no idea what is causing this.

**Comment by silverwind** [comment]
Working fine on my Nexus 5. The only cause I can think of is that you're downloading a large directory. Directory downloads are zipped and sent at the same time, resulting in no file size being sent and a indeterminate progress bar, which is perfectly normal. If you're downloading a directory, how many files are there and what hardware are you running the server on? Anything in the server log?

For further analysis, you could hook up a desktop browser to watch the download request in the Developer tools: https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/remote-debugging?hl=en

**Comment by JustRamon** [comment]
I found the issue. I configured tls to use my normal certificate. Mobile phones need the full chain to fully get https working. I didn't do that, making the download queue itself indefinitely.
