### ISSUE TITLE
Shared Hosting

### ISSUE THREAD

**Issue by UdoKifferbrehl** [silverwind/droppy#262]
Hi, is it possible to install droppy on a Shared Hosting (just upload some files like installing WordPress e.g.)?

**Comment by silverwind** [comment]
No, Node.js isn't like PHP in that regard. You have various options:

- a dedicated server like DigitalOcean
- a app hoster like Heroku
- anything that can run Docker containers
- self hosted on Linux, Windows or Mac. Raspberry Pi works great for a moderate amount of files

**Comment by UdoKifferbrehl** [comment]
OK, thank you so much @silverwind
