### ISSUE TITLE
Unable to upload files !

### ISSUE THREAD

**Issue by rahatray** [silverwind/droppy#271]
Droppy Version 5.1.9 shows Unable to upload when any file is added for uploading.
![droppy](https://cloud.githubusercontent.com/assets/6261301/18913266/c507a11c-85a8-11e6-8e06-367e52f08bc4.png)

**Comment by silverwind** [comment]
Few questions:

1) Which browser are you using?
2) Are you uploading through the button or drag-and-drop?
3) Are you uploading a single file, a directory, or a mix of both?
4) Does https://silverwind.io/uppie/example.html output the file paths (no files are uploaded in that demo)?

**Comment by rahatray** [comment]
Answers to the questions:
1) I am using Mozilla Firefox.
2) I am uploading through the "Add files" buttons.
3) I am uploading a single file.
4) Yes. [https://silverwind.io/uppie/example.html](https://silverwind.io/uppie/example.html) output the file paths (no files are uploaded in that demo) as show in the attached screenshot:
![uppie example](https://cloud.githubusercontent.com/assets/6261301/18946885/af3831a8-8652-11e6-9271-e34ecd13233d.png)

**Comment by silverwind** [comment]
The correct behaviour on the demo should be that the filename(s) are logged below the input element. I've expanded https://silverwind.io/uppie/example.html to support file and directories, can you retry with both buttons and also watch for any errors in the DevTools console?

**Comment by rahatray** [comment]
I have retried with both buttons on your mentioned link. Here are the observations:
1) Mozilla Firefox shows unexpected behaviour and shows "TypeError: files is undefined" in Developer Web Console. Directories button can't add directory. The Directories button acts same as Files button and shows the same "TypeError: files is undefined" in Developer Web Console.
2) Google Chrome shows correct behaviour as you mentioned for both buttons.
For clarification I have attached the screen-shots:

1) Mozilla Firefox Single File upload:
![uppie example - mozilla firefox_single_file](https://cloud.githubusercontent.com/assets/6261301/18987555/f4a2c2ae-8723-11e6-9ed0-b6b9b549dc48.png)

2) Mozilla Firefox TypeError: files is undefined:
![uppie example - mozilla firefox_typeerror files is undefined](https://cloud.githubusercontent.com/assets/6261301/18987602/2353dcf0-8724-11e6-84ac-684db6562187.png)

3) Mozilla Firefox Directories upload:
![uppie example - mozilla firefox_directories](https://cloud.githubusercontent.com/assets/6261301/18987817/59fdd49e-8725-11e6-901d-b447feedefc9.png)

4) Google Chrome Single File upload:
![uppie example - google chrome_singe_file](https://cloud.githubusercontent.com/assets/6261301/18987634/4e03da7c-8724-11e6-9d06-309632005674.png)

5) Google Chrome Directory upload:
![uppie example - google chrome_directories](https://cloud.githubusercontent.com/assets/6261301/18987650/71f41988-8724-11e6-91c5-110f3412aa68.png)

**Comment by silverwind** [comment]
Thanks, I'll investigate further. Could be that I missed something incompatible on the Release line of Firefox. The directory button will work in the next Firefox release (50).

**Comment by silverwind** [comment]
Can reproduce now, it looks like the pref `dom.input.dirpicker` which I had enabled was for some reason interfering with the file picker.

**Comment by rahatray** [comment]
Should I try again to reproduce those in your given link?
Or should I try my local installation of Droppy to check again?

**Comment by silverwind** [comment]
No action needed, I'm building v5.1.11 now which will resolve this bug.

**Comment by silverwind** [comment]
And v5.1.11 is out, please [update](https://github.com/silverwind/droppy#upgrading-a-local-installation-package)!
