### ISSUE TITLE
File operations fail on certain filenames

### ISSUE THREAD

**Issue by RhyLlew** [silverwind/droppy#274]
Hey,

Just a small issue I have finally managed to track down. Some files do not move when dragged from one panel to another. If appears that this happens when the character sequence "++" is used in the file name. It may also be happening with others but ++ is the only one I have been able to find.

Using droppy version 5.1.14, node 4.50

**Comment by silverwind** [comment]
Thanks, this was because of a missed escape before passing strings to `RegExp`. The fix likely resolved a few more issues for files with similar names.
