### ISSUE TITLE
Right panel does not refresh on drag and drop to left panel

### ISSUE THREAD

**Issue by RhyLlew** [silverwind/droppy#275]
Another small one, when dragging and dropping using split view, the righthand panel does not refresh when dragging files from the right to the left. The left will update and it appears the file has copied/duplicated. The file list will refresh if you navigate away from and then back into the folder in question. 

Cut and paste also seems to share the issue.

Droppy version 5.1.14, node v4.50

**Comment by silverwind** [comment]
Cannot seem to reproduce this one. Here's moving two files from left to right and back:

![](https://cloud.githubusercontent.com/assets/115237/19083523/bd12155a-8a62-11e6-88f5-5c823c0d8b12.gif)

Maybe there's special filenames or directory names involved? Any errors logged to the browser or server consoles?

**Comment by RhyLlew** [comment]
I have not had a chance to check logs yet, however it does seem to be intermittent, and more prevalent on large files. The files I first started noticing it on were largish (20-100mb) PDF files. Apart from that some of the folder names have spaces in them, no special characters or anything else of note.

**Comment by silverwind** [comment]
Might have been a browser bug, but if you have more details, I can reopen.
