### ISSUE TITLE
Add folder upload support for Mozilla Firefox

### ISSUE THREAD

**Issue by lemmy** [silverwind/droppy#278]
Uploading folders only works with Microsoft Edge and Google Chrome. Please also support Mozilla Firefox (and Safari).

**Comment by silverwind** [comment]
Directory upload will work in Firefox 50 [ref](https://developer.mozilla.org/en-US/Firefox/Releases/50#Files_and_directories), which will release on 2016-11-08. You can either wait for it or switch to the Beta channel where it should already work.

**Comment by silverwind** [comment]
Alternatively, you may have success with the `dom.dirpicker.enabled` preference in `about:config`.

**Comment by lemmy** [comment]
With `dom.input.dirpicker` set to `true` I successfully uploaded with Firefox (see [https://developer.mozilla.org/fr/Firefox/Releases/42](https://developer.mozilla.org/fr/Firefox/Releases/42))

**Comment by silverwind** [comment]
Thanks, good to know that API still works. Mozilla is a bit indecisive when it comes to directory upload APIs. Anyways, you should probably flip that pref back to its default when 50 releases.

**Comment by vikramaditya-singh** [comment]
Folder Upload works fine in OS X and Windows. But, Firefox doesn't allow it on Linux OS. May I know, why?
