### ISSUE TITLE
Official droppy container doesn't propagate correctly signals since 5.1.19

### ISSUE THREAD

**Issue by gissehel** [silverwind/droppy#279]
One of the main consequences is that **"docker stop"** takes 10 seconds. Indeed, it sends SIGTERM and wait for 10 seconds for droppy to stop. But droppy isn't pid 1 anymore so it never stop. After 10 seconds the whole container is killed, which I suppose is probably ok most of the time, but not the nicest way to exit.

# Steps to reproduce

## pulls
```
$ docker pull silverwind/droppy:5.1.18
$ docker pull silverwind/droppy:5.1.19
```
### context

```
$ docker rm  -v droppy-test
$ docker run -t -i --env UID=1000 --env GID=1000 --hostname droppy --volume /tmp/droppy-test/config:/config:rw --volume /tmp/droppy-test/files:/files:rw --name droppy-test silverwind/droppy:5.1.18
```
### In another shell (because -i)

```
$ docker stop droppy-test
```

### Expected result

Droppy output the line `[INFO] Received SIGINT - Shutting down ...`.
The container stop immedialy.
The new files uploaded via droppy have UID=1000 and GID=1000

### Actual result

The expected result

### context

```
$ docker rm  -v droppy-test
$ docker run -t -i --env UID=1000 --env GID=1000 --hostname droppy --volume /tmp/droppy-test/config:/config:rw --volume /tmp/droppy-test/files:/files:rw --name droppy-test silverwind/droppy:5.1.19
```
### In another shell (because -i)

```
$ docker stop droppy-test
```

### Expected result

Droppy output the line `[INFO] Received SIGINT - Shutting down ...`.
The container stop immedialy.
The new files uploaded via droppy have UID=1000 and GID=1000

### Actual result

No line `[INFO] Received SIGINT - Shutting down ...`.
The docker container wait 10 seconds before exiting. SIGKILL instead of SIGTERM is sent to droppy because the container has been shut down violently.
The new files uploaded via droppy have UID=0 and GID=0

## Note

The Ctrl-C on the interactive **"docker run"** command actually works

**Comment by gissehel** [comment]
The probleme is due to this change https://github.com/silverwind/droppy/commit/cb727f529aa3e58a3c7f599df571f794b6676f92#diff-caf8cdcd3bff3f87fbb3d0be260a2b4eL19

Indeed. For signals to propagate to the main application process, that process needs to be pid 1 inside the container (the command **"docker kill -s TERM"** sends the signal to the process with pid 1, but **"docker stop"** actually does the same).

To start an application from a shell pid 1, and to replace the shell process by the application process, you must use "exec" (shell command).

The trick here, is that "su" (that is needed for other matter) start a new shell. So you must use exec twice. First to replace the startup shell (docker-start.sh) by the "su" process, then again to replace the shell started by su (which also used the "exec" system call, so it's still pid 1) by droppy.

**Comment by gissehel** [comment]
I've played a bit with different command lines, especially to see why I added a **"-s /bin/sh"**. It appears that the shell used by default by `su` is `ash`, and that shell doesn't support putting `exec` inside a `-c` command (while exec seems to work interactively).

but su + sh + setting an environment variable + exec seems to works fine.

**Comment by silverwind** [comment]
Ah, I see what you mean. Before:
```
/ # ps
PID   USER     TIME   COMMAND
    1 droppy     0:00 droppy
   19 root       0:00 /bin/sh
   24 root       0:00 ps
```
After:
```
/ # ps
PID   USER     TIME   COMMAND
    1 root       0:00 ash -c NODE_ENV=production /usr/bin/droppy start --color -f /files -c /config
   10 root       0:00 droppy
   20 root       0:00 /bin/sh
   25 root       0:00 ps
```
`sh` and `ash` both link to `/bin/busybox`.

**Comment by gissehel** [comment]
I just realized that UID and GID doesn't work anymore ! I'll update the problem description.

**Comment by silverwind** [comment]
I'd like to retain the environment variable `NODE_ENV=production` as it triggers optimizations in various Node.js modules. Could you post your current command line so I can play with it?

**Comment by gissehel** [comment]
My current command line is to start version 5.1.18 ;)

I've a working command line that have NODE_ENV=production and still works (I was about to provide a pull request):

```
exec /bin/su -p  -s "/bin/sh" -c "NODE_ENV=production exec /usr/bin/droppy start --color -f /files -c /config" droppy
```

-p is important to change UID GID. Any particular reason to have removed it ?

**Comment by silverwind** [comment]
`-m` (which I removed) and `-p` should be aliases to the same function. And I thought `-p` was easier to remember (preserve). Here from busybox's man page:

```
Options:

    -p, -m  Preserve environment
    -c CMD  Command to pass to 'sh -c'
    -s SH   Shell to use instead of default shell
```

Maybe we can remove the `-s` as we're still using the default shell?

**Comment by gissehel** [comment]
> sh and ash both link to /bin/busybox.

But they don't act the same (which is the principle of busybox, but may expect sh and ash to be very similar: not here!)

**Comment by gissehel** [comment]
> Maybe we can remove the -s as we're still using the default shell?

The default shell is ash and I didn't manage to make it work using ash. If you manage to make it work, just do it. I failed with ash and it worked with sh.

**Comment by silverwind** [comment]
Ah, you're right, I totally missed the fact the everything in `/bin` links to busybox because it's a multi-call binary. Keep it with `sh` then, no reason not to use it.

**Comment by gissehel** [comment]
I just updated the main description with the fact that UID / GID doesn't work anymore... No "droppy" user was provided at the end of the `su` command:

Changes:

> The new files uploaded via droppy have UID=1000 and GID=1000

in the expected result sections 

> The new files uploaded via droppy have UID=0 and GID=0

in the actual result section for version **5.1.19**

**Comment by silverwind** [comment]
FYI, when you're trying to build the container, add something like this after the command so you get a fresh startup script copied over:

```
COPY docker-start.sh /usr/lib/node_modules/droppy/docker-start.sh
```

I recently changed the build to pull the release from npm so that the image gets less layers.

**Comment by gissehel** [comment]
I've seen the changes, but I was about to get caught by that gotcha :) 

(I was literraly about to type **`docker build...`**)

**Comment by silverwind** [comment]
Ah, the fact that UID/GID aren't working might just be because I stupidely removed the `droppy` argument from `su`.

**Comment by gissehel** [comment]
Ok, 
- tests : done
- commit : done
- push : done
- PR : done ( #280 )

On the next merge/release I'll be able to upgrade all my droppy containers to the next release.

**Comment by silverwind** [comment]
A bit unrelated but I played with removing the `-s "/bin/sh"` argument and discovered that because the user has `/bin/false` as default shell, su will try to use just that when the argument is missing:

````
execve("/bin/false", ["false", "-c", "touch /tmp/file"], [/* 12 vars */]) = 0
````
as oposed to providing it:
````
execve("/bin/sh", ["sh", "-c", "touch /tmp/file"], [/* 12 vars */]) = 0
````
So it's indeed very much needed :)

**Comment by gissehel** [comment]
Ok, **I** did the /bin/false thing (when adding the droppy to `/etc/passwd`)

So I tried to replace `/bin/false` by `/bin/sh` and to remove "`-s /bin/sh`" from the `su` command. And it works.

But from a security point of view, having `/bin/false` as the default shell for the droppy user, and explicitly settings `/bin/sh` for `su` make sense: It means that even if an attacker can starts a "default shell" from droppy, it won't success because it's /bin/false (that's the whole purpose of setting /bin/false for every non-interactive users).

So I maintain my PR #280 with the `/bin/false` in the `/etc/passwd` and the `-s /bin/sh` in the `su` command. Feel free to change that if you don't like it.

**Comment by silverwind** [comment]
Thanks, I'll push a new release with your change. Reopening the issue because I can't confirm that

> The new files uploaded via droppy have UID=1000 and GID=1000

is working. It might be because of the particular docker versions I'm using:

On Mac, I have `Docker version 1.12.2, build bb80604, experimental`.
On Linux, I have `Docker version 1.12.0, build 8eab29e`.

Both hosts do create `/files` with correct permission inside and outside the container, but newly created files and directores are UID 0, GID 0 inside and outside. The permissions don't seem to cause any issues with deletion, but I'll still investigate this further.

**Comment by gissehel** [comment]
I can't reproduce that (docker 1.12.1 linux both client & daemon).

My quick guess:
- UID 0 & GID 0 => process run as UID 0 (that's why there would be no problem with deletion)
- Are UID and GID correctly set ? didn't you forget to pass them to the command line ?

Anyway, things intersting to note:
do you have
```
$ ps auxw
[...]
    1 droppy     0:00 droppy
```

or 

```
$ ps auxw
[...]
    1 root       0:00 droppy
```

Do you have a droppy in when executing:

```
$ cat /etc/passwd
[...]
droppy:x:1000:1000:droppy:/app:/bin/false
```

**Comment by gissehel** [comment]
Ho !  The partition that contains /files, is it a Mac one or a Linux one ? If it's a Mac one, is it mounted on Linux with attributes like "only use that uid/gid" ?

I have no idea how does that work in mac, but on Windows with the smb protocol (windows network share protocol), when you mount a folder, you specify the only uid/gid for all the files.

There is no reason to have that thing on Mac because it's much more a unix than Windows, but it may be the reason. 

If that's that, I suppose on linux, chown wouldn't work...

**Comment by silverwind** [comment]
Ah, everything is fine on Linux, it looks I just forgot to build with `--no-cache=true` and my latest change to the startup script wasn't active. Just pulled my released image and permissions of files are correct now. Trying on Mac now.

**Comment by silverwind** [comment]
I certainly see weirdness on mac:

- Files inside the container are created with 0:0 despite the process running as 1000:1000
- Files outside the container are owned by my user, 501:20

Apparently, Docker for Mac does some [workarounds regarding permissions](https://forums.docker.com/t/new-file-sharing-uid-gid-permissions-break-image-portability/8586), so it might be a lost cause. But as longs as it's working as expected on Linux, I'm fine with it.
