### ISSUE TITLE
Preview for images with uppercase in extension doesn't work anymore

### ISSUE THREAD

**Issue by gissehel** [silverwind/droppy#281]
Version: **5.2.6**

# Steps to reproduce
- Upload a jpeg image with the name "Image.JPG"
- Clic on the image

# Expected result
- The image is displayed well

# Actual result
- The image doesn't display at all
- If there is another image in the folder, the next image is displayed instead

# Notes
- All tests been made with official docker images silverwind/droppy (:latest, :5.2.6, :5.1.24, etc.)
- Found by dichotomy that all image until 5.2.0 were working. Regression appeared with 5.2.1
- When the image is called "Image.jpg", it works fine.
- When the image is called "image.JPG", it doesn't work.
- When the image is uploaded with a working version, it can't be displayed by a non working version, thus it's the display and not the upload the problem.

**Comment by silverwind** [comment]
Good catch, thanks.
