### ISSUE TITLE
Embed link for images?

### ISSUE THREAD

**Issue by omidfi** [silverwind/droppy#282]
Hi, is there an option to get the embed link to images easily? 

Also, is it possible to make only uploading of files private, but the files be shared publicly?

**Comment by silverwind** [comment]
Hi. You can embed images by hitting the share button and unchecking "Is DL". The resulting link can be embedded:

![](https://cloud.githubusercontent.com/assets/115237/21523897/5aaf0042-cd12-11e6-9474-2cb24804f627.png)

For the second question, I think it's also solved by the share button. All shared links are available publicly.

**Comment by omidfi** [comment]
Awesome! Thanks a lot <3
