### ISSUE TITLE
Quick and free deployment by now.sh

### ISSUE THREAD

**Issue by omidfi** [silverwind/droppy#283]
Hi, I used http://now.sh to deploy this for free, and it was a very smooth experience using docker. I thought you might want to mention it on the readme as it makes test driving the project extremely easy. 

All needed was: 
  * clone this repo and cd into it
  * npm install -g now
  * now

p.s. I'm not affiliated with now.sh in any way :)

**Comment by silverwind** [comment]
Sorry for never answering this. I don't think I should clutter the readme with information like this. There's a whole lot of tools surrounding the npm ecosystem, and of course I support what I can :)
