### ISSUE TITLE
droppy Docker, SSL, key password

### ISSUE THREAD

**Issue by flexguse** [silverwind/droppy#288]
Hi all,

I'd like to use droppy in combination with SSL. I created a SSL certificate, configured it according to the documentation and I get the error

`droppy    | 2017-02-04 12:21:09 [INFO] Loading resources ...
droppy    | 2017-02-04 12:21:09 [INFO] Loading resources done
droppy    | 2017-02-04 12:21:09 [ERROR] =============== Uncaught exception! ===============
droppy    | 2017-02-04 12:21:09 [ERROR] error:0907B068:PEM routines:PEM_READ_BIO_PRIVATEKEY:bad password read
droppy    |     at Object.createSecureContext (_tls_common.js:85:17)
droppy    |     at Server (_tls_wrap.js:769:25)
droppy    |     at new Server (https.js:26:14)
droppy    |     at Object.createServer (https.js:47:10)
droppy    |     at /usr/lib/node_modules/droppy/server/server.js:244:22
droppy    |     at /usr/lib/node_modules/droppy/server/server.js:1205:9
droppy    |     at Array.forEach (native)
droppy    |     at /usr/lib/node_modules/droppy/server/server.js:1204:23
droppy    |     at /usr/lib/node_modules/droppy/server/server.js:1253:5
droppy    |     at /usr/lib/node_modules/droppy/node_modules/async/dist/async.js:1013:9`

I think the error is caused by the password protected SSL key file.

Where can I configure the password for the SSL key file?

Cheers,
Christoph

**Comment by silverwind** [comment]
I'll add an option for the key password.

**Comment by silverwind** [comment]
In the meanwhile, another option might be to decrypt the key and store it in the configuration directory. Whith permissions are set up properly, the key's security would be equal to storing the passphrase in the configuration.

The only better option would be for me to interactively prompt for the passphrase on startup, but I guess that's not that user-friendly.

**Comment by flexguse** [comment]
Another solution could be a file containing the hashed password and in the configuration the hashed password file is given. Hashing / Encryption could be done in the CLI with some util provided by you.

This surely is not very secure, but at least the password is not present in plain text somewhere in the configuration files.

**Comment by silverwind** [comment]
Hashing won't work in this case. I need to plaintext passphrase to decrypt the key after all. Unless OpenSSL has some way to decrypt a key with just a hash, but I'm not aware of such an option.

**Comment by silverwind** [comment]
Another option (besides interactively asking), could be a passphrase file, similar to [ssl_password_file](https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_password_file). You could put the passphrase in there before (re)starting and delete the file afterwards.

**Comment by flexguse** [comment]
In the first step I'm totally fine with an option in the config-file in which I can give the unencoded key password.

**Comment by silverwind** [comment]
6.0.0 is out with the `passphrase` option.

**Comment by flexguse** [comment]
Thanks a lot for your quick help!
