### ISSUE TITLE
Let's Encrypt challenge configuration

### ISSUE THREAD

**Issue by platipo** [silverwind/droppy#289]
I'm tring to automate certificates renew but even adding in the nginx server block
```nginx
location '/.well-known/acme-challenge' {
		default_type 'text/plain';
		root /tmp/bubbly-authenticator;
}
```
certbot fails to authorize the procedure because it cant't reach the page (404 error).
Any ideas?

P.S. Of course I'm using the configuration written in the wiki

**Comment by silverwind** [comment]
This is more likely a nginx issue, but I'd suggest the standalone challenge if shutting down nginx for a few seconds is an option.

In /etc/letsencrypt/cli.ini
```
authenticator = standalone
standalone-supported-challenges = tls-sni-01
```

And a cronjob to do the challenge:
```
$ crontab -l
@monthly systemctl stop nginx; certbot certonly --force-renew; systemctl start nginx
````

**Comment by platipo** [comment]
Thank you for your kind answer! I managed to write a little script based on  [Bubbly: Certbot with Nginx](https://github.com/eustasy/bubbly/blob/master/bubbly-renew-ssl.sh#L5)
```bash
#!/bin/bash
systemctl stop nginx
certbot certonly \
	--standalone \
	--rsa-key-size 4096 \
	--server https://acme-v01.api.letsencrypt.org/directory \
	--agree-tos \
	--force-renew \
	--dry-run \
	"$@"
systemctl start nginx
```
And a root cronjob:
```
$ crontab -l
@monthly /path/to/script.sh -d example.com -d sub.example.org
```
I hope this is somehow useful to others (or maybe for the wiki).

**Comment by silverwind** [comment]
Standalone auth surely isn't ideal because of the downtime. I'm trying the certbot-nginx plugin right now with my configuration and will update the wiki once I have something working.

So far though, it seems I'm affected by a config parsing bug in that plugin (https://github.com/certbot/certbot/issues/3798).

**Comment by silverwind** [comment]
So after hitting like 4 different certbot bugs, I got `certbot --nginx` to almost work on my extensive nginx config. Looking at the example in the wiki, I can't see the example being affected by any of those.

Maybe you could try the certbot-nginx plugin and share any issues you encounter with my example config. I think it should pretty much work out of the box with simple configs such as that one.

**Comment by platipo** [comment]
Tried slightly modified script today after updating certbot and all went smoothly!
```bash
#!/bin/bash
mkdir -p /tmp/temp-acme
certbot certonly \
	--rsa-key-size 4096 \
	--server https://acme-v01.api.letsencrypt.org/directory \
	--authenticator webroot \
	--webroot-path=/tmp/temp-acme \
	--agree-tos \
	--force-renew \
	"$@"
systemctl restart nginx
```
