### ISSUE TITLE
Support for Matroska video file (.mkv) playback

### ISSUE THREAD

**Issue by Zelosfan** [silverwind/droppy#290]
It would be great to stream .mkv files directly from droppy as it's one
of the most commonly used video formats as well as an open standard.

[https://www.matroska.org/](https://www.matroska.org/)

**Comment by silverwind** [comment]
I support what browsers can play natively. For MKV, it really depends on what video format is contained in the container.

According to [this](http://stackoverflow.com/a/16941573/808699), it is possible get get *some* MKVs to play in the browser by serving them with the WEBM mime type, so I did that. From these [samples](http://jell.yfish.us/), I was able to play the H264 MKV in Chrome, but not in Firefox. I guess this is all that can be done until browser support improves.
