### ISSUE TITLE
/usr/bin/droppy: Permission denied

### ISSUE THREAD

**Issue by mhdev90** [silverwind/droppy#291]
`docker run --name droppy -e UID=1000 -e GID=1000 -p 127.0.0.1:8989:8989 silverwind/droppy`

Any Ideas?

**Comment by silverwind** [comment]
Hmm, something about UID/GID, investigating.

**Comment by silverwind** [comment]
6.0.6 is out with the fix, sorry about that.

**Comment by mhdev90** [comment]
Nice work, thanks!
