### ISSUE TITLE
Run Droppy from a subdirectory

### ISSUE THREAD

**Issue by andyforceno** [silverwind/droppy#293]
This is really an nginx configuration issue, but I thought someone here could help me. I'd like to be able to browse to http://my-domain.com/droppy to access Droppy. Currently, it is accessible only via the root directory. I've tried a few rewrite rules, but most broke Droppy, or did nothing. I'm using the recommended nginx configuration for Droppy, plus a rewrite rule:

    location ^/droppy {
    rewrite ^/droppy/(.*)$ /droppy/$1/ last;
    # rewrite ^/droppy(.*) /$1/login/ break;
    }

Neither of those rules break Droppy, but neither have the intended effect, either. I suspect the issue is that I'm not as well-versed in nginx as I could be. Any help is appreciated :-)

**Comment by silverwind** [comment]
This should work for you:

```nginx
location /droppy/ {
  proxy_pass http://droppy/;
}
```
The trailing slashes on both the `location` and the `proxy_pass` are significant.

**Comment by andyforceno** [comment]
I'm embarrassed to have missed that. Works like a charm, thanks!
