### ISSUE TITLE
User manager

### ISSUE THREAD

**Issue by Albatrosicks** [silverwind/droppy#296]
It's not possible to change user password and username for admins and themselves. And admin can toggle `privileged` flag only in `db.json`

**Comment by r15ch13** [comment]
To change a users password add a new user with the same name and a different password (and privileged flag). The old user will be overwritten.
I implemented and option to configure the privileged flag with #301

**Comment by silverwind** [comment]
Yes, the add function actually overrides a previous user. I will make that more clear in the options interface. And thanks to @r15ch13, we can now set the privileged flag from the options!
