### ISSUE TITLE
Docker SSL problem

### ISSUE THREAD

**Issue by joltcan** [silverwind/droppy#298]
Hi!

When using NGINX (and the config from the wiki) together with SSL, droppy isn't readable over wss/ws websocket:

From Chrome:
```

VM729:35 Refused to connect to 'wss://droppy.example.com/!/socket' because it violates the following Content Security Policy directive: "connect-src 'self' ws://10.20.30.1:8989 wss://10.20.30.1:8989".

VM729:35 Uncaught DOMException: Failed to construct 'WebSocket': Refused to connect to 'wss://droppy.example.com/!/socket' because it violates the document's Content Security Policy.
    at WrappedWebSocket (<anonymous>:35:21)
    at u (https://droppy.example.com/!/res/client.js:2:19559)
    at https://droppy.example.com/!/res/client.js:4:15199
    at https://droppy.example.com/!/res/client.js:4:18123
    at https://droppy.example.com/!/res/client.js:4:19250
```
Is it possible to add this as an option to the config?

**Comment by silverwind** [comment]
Are your forwarding the `Host` header in nginx? I assume one of these directives might work for you:

```nginx
proxy_set_header Host $http_host;
proxy_set_header X-Forwarded-Host $http_host;
```

Please try with just `Host` first, and let me know which one worked.

**Comment by silverwind** [comment]
Oh, and because you mentioned using the wiki config: Does your nginx's `server_name` match the adress you're going to in the browser? I really wonder where that `10.20.30.1` is coming from. It must come be from one of those headers.

**Comment by joltcan** [comment]
So annoying. Works great via VPN from home, but is stuck with that error message when running it from my work computer (where I set everything up today). I guess I need to investigate if the proxy at work does something funky. 

The server_name matches the name I use, so that shouldn't mess things up.

**Comment by silverwind** [comment]
Here's the code that sets this CSP header: https://github.com/silverwind/droppy/blob/9134108dd0af841f35491466b5d7d69d84c7884b/server/utils.js#L314-L320

The `10.20.30.1` is extracted from the `X-Forwarded-Host` or `Host` headers received. I guess I could add an option to send these CSP headers, but I'd be interested in what your proxy does exactly to these headers (or if it sends any additional).

**Comment by silverwind** [comment]
Decided to disable the `connect-src` policy because it's causing too much issues. Let me know if you still find out anything about the proxy issue though.

**Comment by joltcan** [comment]
Hi! You can close this, I'm not able to reproduce from work regardless. Not sure why it didn't work.
