### ISSUE TITLE
droppy 6.3.17 running into problem.

### ISSUE THREAD

**Issue by t-k-** [silverwind/droppy#306]
.:.
    :::  .:::::.   droppy 6.3.17 running on node 6.5.0
  ..:::..  :::     config at /home/tk/.droppy/config
   ':::'   :::     files at /home/tk/.droppy/files
     '

[ERROR] =============== Uncaught exception! ===============
[ERROR] TypeError: Expected options to be either an object or a string, but got function instead
    at throwOptionsError (fs.js:81:9)
    at Object.fs.writeFileSync (fs.js:1326:5)
    at write (/home/tk/Desktop/blog-feeds-incr-sync/tkarchive/node_modules/droppy/server/db.js:123:6)
    at /home/tk/Desktop/blog-feeds-incr-sync/tkarchive/node_modules/droppy/server/db.js:21:11
    at /home/tk/Desktop/blog-feeds-incr-sync/tkarchive/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by silverwind** [comment]
Fixed that mistake. 6.3.18 is building and should be available in a few minutes.

**Comment by t-k-** [comment]
droppy does not have any basic test covered? Hey, this is terrifying if droppy does not check if it is usable before publishing.

**Comment by silverwind** [comment]
No automatic tests yet. I do test on Mac and Linux on latest Node.js, where apparently this issue wasn't showing.

**Comment by t-k-** [comment]
So the problem is old version node complains about `writeFileSync` misusage?
