### ISSUE TITLE
Is websocket a requirement?

### ISSUE THREAD

**Issue by t-k-** [silverwind/droppy#309]
I see droppy is using websocket, but is there any fallback for a browser does not support websocket?

**Comment by silverwind** [comment]
Yes, it's a requirement. Pretty much all messaging between client and server happens over websockets, so if those don't work, you won't be seeing any files. A fallback might be a good idea, but I don't really see much of a point, all modern browsers support them.

**Comment by t-k-** [comment]
@silverwind Thank you for your answer. I am asking because I want to do some reverse proxy and host droppy in a local network environment. WebSocket is currently the hurdle.

If so, do you have any option to configure the port on which droppy websocket is listening (I see current port is 80)? If I can control this, it is much easier to write Nginx config rule to distinguish websocket traffic and HTTP traffic, so that I can use wstunnel for example, to tunnel websocket traffic.

**Comment by silverwind** [comment]
The server accepts websocket handshakes on any URL and the client connects to `/!/socket` specifically so proxies like Apache can detect the handshake attempt. See the examples on the wiki:

https://github.com/silverwind/droppy/wiki/Apache-reverse-proxy
https://github.com/silverwind/droppy/wiki/Nginx-reverse-proxy

As you can see, nginx needs to knowledge of the handshake URL, it'll forward all handshakes with these directives:

```nginx
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $http_connection;
```

I'd prefer the Apache configuration to also be URL-less, but I'm not sure it's possible.

**Comment by t-k-** [comment]
@silverwind  I feel I have to explain my situation a little bit. I am hosting droppy in a local network, and I want to find a way to establish reverse proxy between droppy and VPS (public network). So that when I visit http://public-VPS/r/droppy from Internet, it would be the same as accessing http://localhost/droppy on my local network.

Currently HTTP proxy is working (I am using Socks5 protocol). But to get WebSocket working, what I am trying to do now is to direct any WebSocket URL (/r/droppy/!/socket) to some WebSocket proxy:
```
        location ^~ /r/droppy/!/socket {
            proxy_pass http://127.0.0.1;
                
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            rewrite ^/r/(.*) /$1 break;
            proxy_redirect off;
        } 
```
However, it does not work for unknown reason.

Any idea?

**Comment by t-k-** [comment]
Update: I notice the [INFO] log from droppy prints: 
```
2017-06-12 21:20:10 [INFO] 127.0.0.1:34272 GET /!/socket [401] Unauthorized WebSocket connection rejected.
```

So I dive into source code and notice this is because WebSocket request (from proxy) does not contain cookie (my config.public is false). See:
[https://github.com/silverwind/droppy/blob/3feedd168db386a0be7b6d9d12c779de6d502569/server/server.js#L392](https://github.com/silverwind/droppy/blob/3feedd168db386a0be7b6d9d12c779de6d502569/server/server.js#L392)
[https://github.com/silverwind/droppy/blob/3feedd168db386a0be7b6d9d12c779de6d502569/server/server.js#L1341-L1343](https://github.com/silverwind/droppy/blob/3feedd168db386a0be7b6d9d12c779de6d502569/server/server.js#L1341-L1343)

Then I log the cookie:
```javascript
log.info(info.req, {statusCode: 12345}, JSON.stringify(info.req.headers.cookie));
```
I get the request cookie from proxy:
```
"__utma=96992031.1088174150.1495638662.1495638662.1495638662.1; 
__utmz=96992031.1495638662.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); 
olfsk=olfsk618989647405076; hblid=1tZRktuFXNpSnQIN3M4ps0H0Ma3RhKo2; 
_ga=GA1.1.1088174150.1495638662"
```

Is different from the request cookie from normal accessing:
```
"s=gone; s=DF4UcEm+606BoIIdb9HPEhoqhm/1GjkeFjw5l4/0MZZYx0+Q; 
__utma=96992031.1088174150.1495638662.1495638662.1495638662.1; 
__utmz=96992031.1495638662.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); 
olfsk=olfsk618989647405076; hblid=1tZRktuFXNpSnQIN3M4ps0H0Ma3RhKo2; 
_ga=GA1.1.1088174150.1495638662"
```

The latter has a `s=gone; s=DF4UcEm+606BoIIdb9HPEhoqhm/1GjkeFjw5l4/0MZZYx0+Q;`

What this string for? And why a proxy not passing this cookie string?

**Comment by t-k-** [comment]
Another update:

After I configure public to true (config.public = true), I get repeated message like below when accessing through proxy. 
```
2017-06-12 21:49:35 [INFO] [::ffff:127.0.0.1]:51340 WebSocket [connected]
2017-06-12 21:49:35 [INFO] [::ffff:127.0.0.1]:51340 WebSocket [disconnected] (CSFR prevented or server restarted)
```

**Comment by silverwind** [comment]
The cookies `s` are droppy's cookies. the `s=gone` shouldn't be there, it's only set by the server when logging out. It's meant to override the previous token, but apparently there's a bug with that mechanism, I'll check.

As for why the cookie doesn't reach the server, I'm a bit out of ideas. Can you check in the browser devtools if the `s` token is actually sent with the `!/socket` request? Also, I'd first delete all `s` tokens in that cookie manually and then log in again.

**Comment by silverwind** [comment]
Oh, and 

> CSFR prevented

this is normal if you restart the server with an active client connected, as CSFR tokens aren't persistent yet. The error should be gone after a page reload on the client.

**Comment by silverwind** [comment]
Okay I think I know your issue. droppy restricts the cookie via the `path` attribute for security reasons, as your path is changing during proxying, you also need to rewrite the cookie path. In nginx:

````
proxy_cookie_path /r/droppy/ /droppy/;
````
(if that doesn't work, drop the trailing slashes)

**Comment by t-k-** [comment]
I tried `proxy_cookie_path` in many different ways, but it still does not work. It still keeps logging:
```
2017-06-12 21:49:35 [INFO] [::ffff:127.0.0.1]:51340 WebSocket [connected]
2017-06-12 21:49:35 [INFO] [::ffff:127.0.0.1]:51340 WebSocket [disconnected] (CSFR prevented or server restarted)
```
These are some variations that I have tried:
```
proxy_cookie_path /r/droppy/ /droppy/;
proxy_cookie_path /r/droppy /droppy;
proxy_cookie_path /r/droppy/ /;
proxy_cookie_path /r/droppy /;
````
Also I find [nginx manual](http://nginx.org/en/docs/http/ngx_http_proxy_module.html) only specifies one path argument for `proxy_cookie_path`. We may use it in a wrong way I guess.

**Comment by t-k-** [comment]
Update: I tried capturing WebSocket packets using Wireshark, the normal request and the proxy request are almost identical except the proxy request misses `token` field in message:

normal request:
```
{"vId":null,"type":"REQUEST_SETTINGS","token":"93a751c9da62c88909d08e79b42eba12"}
```

proxy request
```
{"vId":null,"type":"REQUEST_SETTINGS","token":""}
```

After diving into source code again, I confirm this is the reason:
https://github.com/silverwind/droppy/blob/3feedd168db386a0be7b6d9d12c779de6d502569/server/server.js#L413-L416

**Comment by silverwind** [comment]
Yeah, you're not getting a CSFR token because that one is obtained on a ajax request that verifies the presence of a cookie (event public mode uses cookies).

Can you show the reponse headers to the `/login` POST request, particularly the `Set-Cookie` response?

**Comment by silverwind** [comment]
Actually, no, I think you should be able to get a token without a cookie as long as public mode is on. Anyways, check the response of the `/!/token` ajax request, that's where its coming from.

> Also I find nginx manual only specifies one path argument for proxy_cookie_path

It's two arguments, `proxy_cookie_path path replacement;`. As I understand it, it's a simple search and replace operation over the path attribute (As seen in Set-Cookie).

**Comment by silverwind** [comment]
Okay I think there's actually a bug in my ajax requests, they're not respecting the root path for certain requests (so your token request goes to `/!/token` instead of `/droppy/!/token/`, which fails. Will fix.

**Comment by t-k-** [comment]
My public mode is on, so there seems to be no request to `/login`.

Using Chrome inspect/network, I get the request/response headers to `/!/token`:
```
GET /r/droppy/!/token HTTP/1.1
Host: 127.0.0.1
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
x-app: droppy
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Accept: */*
Referer: http://127.0.0.1/r/droppy/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,zh;q=0.6,zh-CN;q=0.4,zh-TW;q=0.2
Cookie: __utma=96992031.1088174150.1495638662.1495638662.1495638662.1; __utmz=96992031.1495638662.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); olfsk=olfsk618989647405076; hblid=1tZRktuFXNpSnQIN3M4ps0H0Ma3RhKo2; _ga=GA1.1.1088174150.1495638662
```
```
HTTP/1.1 200 OK
Server: nginx/1.10.1
Date: Mon, 12 Jun 2017 16:46:14 GMT
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/7.0.10
```
(Chrome says "the request has no response data available")

BTW. Thank you for pointing out what `proxy_cookie_path` is perhaps doing under the hood.

**Comment by t-k-** [comment]
Great to know you find a clue! It is late in my timezone, I will get back to you if you need more debug information. Thank you so much.

**Comment by silverwind** [comment]
Okay. I'm not totally certain my fixes will work for you as your token request already looks correct, but there were certainly wrong requests being sent, which will be fixed in 6.5.4 which should be available in 10 minutes. Please try that and let me know!

**Comment by t-k-** [comment]
Another update. After I comment these lines, it works. 
```javascript
      if (!csrf.validate(msg.token)) {
//        ws.close(1011);
//        return;
      } 
````
I tried to download a pdf and view a PNG file, it seems everything is working. I just do not know if there is any consequence (except undermined security) after commenting these two lines.

**Comment by t-k-** [comment]
Sorry I have to sleep I think, will pull your code (6.5.4) perhaps some time tomorrow, and get back to you then. Thank you for helping me.

**Comment by silverwind** [comment]
With CSFR validation disabled on the websocket, it's possible that someone from a different site can connect to droppy's Websocket and access the data there. Not much an issue if you're on public mode anyways, but it could be dangerous when private.

Your token request with the empty response is still a mystery to me. That route should either deliver the token in plain text or give a 403 response. If it still doesn't work after the update, try adding some logging to the token route.

**Comment by t-k-** [comment]
Hi, I tried droppy 6.5.4 running on node 6.5.0. The login page freezed when I clicked "Sign in" button. Here is the error I got from chrome console:
```
client.js:1 Uncaught TypeError: Failed to construct 'Headers': No matching constructor signature.
```

And the error occurs at near `var t=new Headers(e.headers);` in client.js.

**Comment by t-k-** [comment]
I revert back to droppy 6.3.18 and set `public = false` again. I find the response to normal droppy `POST /droppy/!/login HTTP/1.1` request has Set-Cookie` header, but proxy response does not have that. So I agree that there is possibly some problem with my PHP proxy script, I will check this and get back to you then.

**Comment by t-k-** [comment]
OKay, I finally get the login authorization partially working...
It turns out to be indeed the problem of my PHP proxy script (revprox.php). My PHP script almost always takes the same header return as proxy response. This causes the login response header not including `Set-Cookie` field(s). After changing my revprox.php to something like the following, I can successfully login.

```php
curl_setopt($ch, CURLOPT_HEADER, true);
$ret = curl_exec($ch);

/* set response header */
list($ret_header, $ret_body) = explode("\r\n\r\n", $ret, 2);
$ret_header_arr = explode("\r\n", $ret_header);
foreach ($ret_header_arr as $hf) {
    header($hf);
}
/* return response body */
echo $ret_body;
```

However, after login, I cannot view image or download any files, the `GET http://127.0.0.1/r/droppy/!/token` request returns "401 Unauthorized". I will keep investigating on this.

**Comment by t-k-** [comment]
Sorry, the problem is all about my PHP script. 

Since this thread gets pretty lengthy, I will conclude the problems we have encountered as below:
- [x] websocket port configureation (No need, I know how to do websocket reverse-proxy now)
- [x] websocket reverse proxy (I did it)
- [x] proxy request does not contain `s` cookie (My bad, PHP script not doing `Set-Cookie` proxy)
- [x] CSFR validation not passing (After I correct my PHP script, this gets passed now)

**Comment by t-k-** [comment]
I will close this issue for now. Will open another two issues for new problems I find.
