### ISSUE TITLE
Droppy 6.5.4 cannot "Sign in".

### ISSUE THREAD

**Issue by t-k-** [silverwind/droppy#310]
Droppy 6.5.4 running on node 6.5.0. The login page freezed when I clicked "Sign in" button. Here is the error I got from chrome console:
```
client.js:1 Uncaught TypeError: Failed to construct 'Headers': No matching constructor signature.
```

And the error occurs at near `var t=new Headers(e.headers);` in client.js.

(droppy 6.3.18 running on node 6.5.0 does not have this problem)

**Comment by silverwind** [comment]
Which browser and version is this and does `new Headers()` show an error when you enter it into the browser console?

**Comment by silverwind** [comment]
Ah, reproduced. It's a Chrome bug that got fixed in https://chromium.googlesource.com/chromium/src.git/+/458671c24ea47bec9940f1db3034b711a78d5e8c, and the Canary build I use already has the fix. Will workaround.
