### ISSUE TITLE
Not authorized to download.

### ISSUE THREAD

**Issue by t-k-** [silverwind/droppy#311]
Droppy 6.3.18 running on node 6.5.0.

Photo preview, text file editing, folder creating, deleting files... these work fine. But when I try to download files (e.g. PDFs) or click any "Download ZIP" button, the downloading process will eventually fail.

I have checked this issue on Wireshark, the request `GET /!/type/campus-map.pdf` (which contains HTTP `Cookie:` header) returns `200 OK`, however, the following `GET /!/dl/campus-map.pdf` request does not contain `Cookie:` header, thus I get a `HTTP/1.1 401 Unauthorized` return code.

My guess is that some client Javascript forgets to send cookies in the following `/!/dl/*` request, but I am not sure about this...

**Comment by t-k-** [comment]
Strange, only Chromium browser (Version 52.0.2743.116 (64-bit)) has this problem so far.
I tried Firefox and chrome on my mobile phone, there is no problem to download files.
(After I restart the browser, clear cache and "hard reload", still not working on my Chromium browser)

Any idea.

**Comment by silverwind** [comment]
Javascript has no control over the headers (including Cookie) that are sent with download requests, it happens completely by Chrome itself.

Your description reminds me strongly about a Chrome bug I filed: https://bugs.chromium.org/p/chromium/issues/detail?id=648043#c14

Try this patch please:

````diff
diff --git a/server/cookies.js b/server/cookies.js
index a51992b3..b46f554f 100644
--- a/server/cookies.js
+++ b/server/cookies.js
@@ -5,7 +5,7 @@ const db      = require("./db.js");
 const utils   = require("./utils.js");

 // TODO: set secure flag on cookie. Requires X-Forwarded-Proto from the proxy
-const cookieParams = ["HttpOnly", "SameSite=strict"];
+const cookieParams = ["HttpOnly"];

 cookies.parse = function(cookie) {
   const entries = {};
````

**Comment by t-k-** [comment]
Yeah it works now. So why are we using `"SameSite=strict"`?

**Comment by silverwind** [comment]
It's an important security flag and the fact it works means that bug needs to be reported to Chromium again.

**Comment by silverwind** [comment]
@t-k- care to post a Chromium Bug with a reference to https://bugs.chromium.org/p/chromium/issues/detail?id=648043? The symtoms are exactly the same and I think it must've regressed.

**Comment by silverwind** [comment]
Actually, I just noticed your Chromium is vastly out of date. It works for me on Chromium 61.0.3130.0, you should update :)

**Comment by t-k-** [comment]
You are right. Ironically, the reason I have discovered Droppy is because I want to build a privately-hosted cloud system to backup all my data before I sync/upgrade my Arch Linux based desktop to make sure I will not lost any data if pacman gets screw-up.

**Comment by silverwind** [comment]
Thank you too for highlighting those bugs :)
