### ISSUE TITLE
Public share improvement?

### ISSUE THREAD

**Issue by amenolo** [silverwind/droppy#314]
First thing first: awesome project!

Pleasantries aside, let's cut to the chase: code installed on Apache 2.4.18 with proper mods & settings (as explained in the wiki itself), **public mode on false**.

Well...

Expected behavior by me: shared links are public, litteraly, one doesn't need login to reach them properly (preferred choice), or else appears a login request

Actual behavior: if one isn't logged in, shared links lead to a white page with Droppy log showing error [401] (authentication required)

I guess actual behavior is the planned one, but...do you plan to improve the feature, by any chance?

Thanks

**Comment by silverwind** [comment]
That sounds like a bug, I'll try to replicate.

**Comment by silverwind** [comment]
Fixed in v6.6.8. I'm sorry I didn't notice it earlier those links they were broken.

**Comment by amenolo** [comment]
Just tried: now it's working flawlessly, of course!

Very kind of you 👍

**Comment by amenolo** [comment]
Sorry, still me...I spoke too soon...after further tests, I found out another strange behavior: in both public and private mode, directory share link (without "triggered download" flag) leads to a file (which is a proper zip file of the direcotry, in fact) named like the last five random letters of the link itself, instead of the directory listing, as I guess one would expected.

Execution log reports a standard "**GET /$/<last 5 letters> [200]**".

If required, I'll open another issue.

Thanks!

**Comment by silverwind** [comment]
Ah, there was a authentication check on directory downloads that I missed, fixed now and will be released as v6.6.9 in a few minutes.

I also changed the trigger download functionality on directory downloads. The links will now always result in the correct filename and when "Is DL" is not checked, the download will be sent "inline", which leaves it to the browser to decide what to do with the zip (They'll most likely download it anyways unless they can display the zip "inline").

**Comment by amenolo** [comment]
Bingo! Very appreciated your responsiveness 👍
