### ISSUE TITLE
Feature request: Click on audio file to play by default

### ISSUE THREAD

**Issue by tungel** [silverwind/droppy#317]
Hi, I just came across this app and I really like it! Thank you for your great work!

I have just one minor concern regarding the default behaviour when clicking on audio file. Currently the default action is to download the audio file. However I find it's a bit inconvenient because user would most likely want to play the audio file rather than downloading it. I understand that there is an icon on the left to play the file, but for an average user using the tool on her mobile phone, it's rather confusing.

**Comment by silverwind** [comment]
I agree, it's more intuitive that way.

I thought about removing the hover button (it doesn't work on mobile), but I guess I'll keep it around as an indication on what a click will do. I'll add something similar to video/audio as well. Thanks!

**Comment by tungel** [comment]
Cool. Thanks for merging it!
