### ISSUE TITLE
Cannot host https on any other port besides 443

### ISSUE THREAD

**Issue by cp1797** [silverwind/droppy#319]
It's possible to host http on any port of my choosing, but https on a port other than 443 gives no response. Am using a cert from Let's Encrypt. 

Am running a Windows machine. Kindly assist

**Comment by silverwind** [comment]
I found one possible problem: Errors during socket creation weren't logged. Try again with v6.6.12 and you should probably see a relevant error.

As to what your error is, I can only guess, but this configuration works for me (cert and key files in the same directory as the script):

````json
    {
      "host": ["0.0.0.0", "::"],
      "port": 8888,
      "protocol": "https",
      "cert": "domain.crt",
      "key": "domain.key"
    }
````

**Comment by cp1797** [comment]
@silverwind great! Will give it a shot and let you know

_Sent from my Lge LG-H870DS using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cp1797** [comment]
#320
