### ISSUE TITLE
Nginx reverse proxy no such file or directory

### ISSUE THREAD

**Issue by andyforceno** [silverwind/droppy#325]
I'm fairly certain this is a configuration issue on my end, but here goes: I'm suddenly getting errors from nginx when I visit my Droppy (mydomain.com/droppy/). The page loads, but the formatting looks off, with icons and text all overlayed on each other.  

It seems nginx is looking in /var/www/droppy/ for css and js files, but that location doesn't exist. Prior to this, Droppy was running fine for months. I've been over my nginx.conf and droppy.conf, and nothing is amiss. My Droppy config is identical to the one you provide, except that I access Droppy from a subfolder.  Out of curiosity, where are those files actually served from? 

I've tried updating Droppy, and then I tried re-installing it, but I'm still seeing the same errors. Here's one as an example:
`request: "GET /droppy/!/res/client.js HTTP/1.1", host: "mydomain.com"
2017/08/22 17:36:57 [error] 12547#0: *170 open() "/var/www/droppy/!/res/style.css" failed (2: No such file or directory)`

**Comment by silverwind** [comment]
So you solved it?

Client files are served on the `/!/res/` path, which is populated by static entries from these lines:

https://github.com/silverwind/droppy/blob/master/server/resources.js#L108-L170

**Comment by andyforceno** [comment]
I thought I had solved it. I think many node modules have become uninstalled, possibly when I reinstalled node to correct another issue last week. When I reinstalled droppy, these were not installed. I just installed handlebars manually. Is there a command I can execute that will install all dependencies?

**Comment by silverwind** [comment]
Try

```
npm cache clean --force
npm uninstall -g droppy
npm install -g --production droppy
``` 

Alternatively, you can try to go to the installation directory and run a manual dependency installation there:

```
cd $(dirname $(realpath $(which droppy)))
npm install --production
```

Finally, you could also try running of the git version, but in that case, you need development dependencies to build `dist/cache.json` (achieved by omitting `--production`):

````
git clone https://github.com/silverwind/droppy
cd droppy
npm install
./droppy build
./droppy.js start -c ... -f ...
````

**Comment by andyforceno** [comment]
I tried the first set of commands you gave, and it seemed to install everything. However, I'm running into the same issue. I'm still not sure what is causing this, but I noticed that I can access Droppy fine from the local network IP, which circumvents nginx entirely. When I access via my domain, I just get a blank gray/black page, and errors in nginx's error.log about .css and .js files. 

I haven't touch my nginx config in months, I can't imagine what would be different all of a sudden.  I really don't think this is a problem with Droppy per se, as I'm seeing the same thing from the web app Calibre-web. I noticed none of the PHP-based web apps I am running have this problem, though. *Shrugs* I think I'll declare it a lost cause for now.

**Comment by silverwind** [comment]
Can you post the relevant sections of your `location` block? I'm pretty certain something must be wrong there. A common fault is when you forget the trailing slash in `proxy_pass` or the `location` declaration itself. Make sure both have trailing slashes.

**Comment by andyforceno** [comment]
location /droppy/ {
      proxy_pass http://droppy-upstream/;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Real-Port $remote_port;
      proxy_http_version 1.1;
      proxy_cache off;
      proxy_buffering off;
      proxy_redirect off;
#      proxy_request_buffering off;
      proxy_buffer_size 64k;
      proxy_buffers 8 32k;
      proxy_ignore_client_abort on;
      proxy_connect_timeout 7200;
      proxy_read_timeout 7200;
      proxy_send_timeout 7200;

	add_header Strict-Transport-Security "max-age=15552000; includeSubDomains";
	add_header X-Content-Type-Options nosniff;
	add_header X-Frame-Options "SAMEORIGIN";
	add_header X-XSS-Protection "1; mode=block";
	add_header X-Robots-Tag none;
	add_header X-Download-Options noopen;
	add_header X-Permitted-Cross-Domain-Policies none;
	add_header Access-Control-Allow-Origin *;
        }

Droppy-upstream is specified in nginx.conf as localhost:8989

**Comment by silverwind** [comment]
Looks alright. What URL does the browser show on the broken page `/droppy` or `/droppy/`? Do observe any redirects with `curl -i <url>`?

**Comment by andyforceno** [comment]
Browser shows URL with the trailing slash. Curl - i doesn't show any redirects. Also, I expected to see some errors in the Chrome developer console, but there are none.

**Comment by silverwind** [comment]
Do you have a `root` statement somewhere outside the location block? If so, try removing it.

**Comment by andyforceno** [comment]
I removed the root statement and reloaded the nginx configuration, but Droppy still isn't loading properly, and I'm still seeing the same errors in the nginx error log. I will probably reinstall nginx this weekend to see if that helps (I want to compile it with Pagespeed support, anyway). Hopefully, that will help.

**Comment by silverwind** [comment]
Okay. I'm pretty certain that something outside the location block must be interferring. I'd suggest you remove or comment out everything except droppy's location and then try again. Once it's working, add stuff back in.

**Comment by andyforceno** [comment]
Thank you for your help, you were correct. I had suspected the issue was related to enabling browser caching, I just didn't think I would find it in the config for another virtual host. I guess enabling browser caching for Droppy is no good. Here's the problem:

    location ~*  \.(jpg|jpeg|png|gif|ico|css|js|pdf)$ {
    expires 7d;
    }

Of course the issue is that I'm specifying all locations, when it should be restricted to just one. I've disabled it for now, it's nice to have things back to normal. Thanks again.

**Comment by andyforceno** [comment]
Spoke too soon. Getting authentication errors for all of my users, and I know the passwords are good. May be a permission issue on my system, I'll investigate further. I do get the login page now though, I wasn't getting that before.

**Comment by silverwind** [comment]
Setting cache headers alone shouldn't lead to issues like you described. Your issue had to do with request routing, so I suspect it was a `rewrite`, `alias` or `root` statement that interferred.

Nginx location blocks are kind of tricky and do unexpected things sometimes. I generally recommend to use a `server` and dedicated subdomain for each service you run.

**Comment by andyforceno** [comment]
The issue was that I had a location that matched all locations in one of the configs in /.. /sites-enabled/, and that statement caches js, css, and various other statics files. 

I need to redo my nginx, it does have some issues (complains about server blocks anywhere other than nginx.conf). If it was properly configured this would  not have been an issue. 

Thank you for your help despite this not being an issue with Droppy. I appreciate the time you took to help.
