### ISSUE TITLE
Need a refresh button?

### ISSUE THREAD

**Issue by t-k-** [silverwind/droppy#327]
Environment:
> droppy 6.8.0
> node 8.2.1

When I disable file watch, I find Droppy unable to reflect newly created file (created manually by `mkdir` command) unless I create another new file under that folder again (this time using Droppy UI). I guess this is because file watch feature is disabled, however, in my case I really do not want file watch because it takes forever to initialize for large directory. Can we have a refresh button to manually refresh and let Droppy examine possible newly created files under specific directory?

Thank you!

**Comment by silverwind** [comment]
I could see such a button being added when watching is disabled, but I'm also interested in the kind of issues you're having with enabled watching. What kind of delays are we talking about and how many files do you have in these directories?

Maybe I'll also try another watcher implementation like https://github.com/Axosoft/nsfw, to see if it's more lightweight than the chokidar module.

**Comment by t-k-** [comment]
I currently use Droppy to host and manage essentially all my personal data. It is hard to evaluate how many files I have now. The complains that Droppy has I have also reported in this issue: https://github.com/silverwind/droppy/issues/307

**Comment by t-k-** [comment]
It is very desired to have such a button, otherwise the watch=false config basically will not be complete to use I assume.

**Comment by t-k-** [comment]
@silverwind Thank you so much for making this change. I love this `Reload view` button, it works like magic!
