### ISSUE TITLE
e.toggleComment is not a function (commenting not working)

### ISSUE THREAD

**Issue by JeremyJaydan** [silverwind/droppy#330]
Hey so when I input `CTRL + /` to comment a line within the editor, it simply does not work. I thought it just wasn't a feature until I noticed the below error in the console:
```
VM52:1 Uncaught TypeError: e.toggleComment is not a function
    at d.(anonymous function) (<anonymous>:1:205065)
    at xo (<anonymous>:1:84885)
    at <anonymous>:1:85728
    at oo (<anonymous>:1:81693)
    at bo (<anonymous>:1:85123)
    at wo (<anonymous>:1:85327)
    at Co (<anonymous>:1:85700)
    at Vo.Lo (<anonymous>:1:85972)
    at HTMLTextAreaElement.<anonymous> (<anonymous>:1:53285)
```

I'm not sure if it's related to CodeMirror.
 
Versions: `droppy 6.8.9` `node 6.11.3` `CodeMirror 5.30.0`

P.S. I found droppy a few days ago and I'm absolutely loving it, made the switch as my main code editor!

**Comment by silverwind** [comment]
Thanks. I was actually missing the CodeMirror addon for comments. I also added a shortcut `Ctrl-Space` for comment toggling as `Ctrl-/` is not typeable on a german keyboard.

Let me know if you're missing any more CodeMirror functionality.
