### ISSUE TITLE
express example is not working

### ISSUE THREAD

**Issue by Worie** [silverwind/droppy#336]
Hi there!

I cannot get the express example to work.

I've created an empty project, installed 
`npm install --save express droopy`

and set the contents of `app.js` to 
```js

"use strict";
const app = require("express")();
const fs = require("fs");

// alias the module. replace ".." with "droppy" when used as module
const droppy = require("droppy");

// initialze droppy with a config object
const droppyOnRequest = droppy({
  configdir: "./config",
  filesdir: "./files",
  logLevel: 3,
  debug: true,
  public: true
});

// write a test file
fs.writeFileSync("./files/test.txt", "Just a test!");

// start the app on http://localhost:8989/ or a port of your choice
app.use("/", droppyOnRequest).listen(process.env.PORT || 8989);
```

Unfortunately, when heading to `localhost:8989` all I get is [this](https://i.imgur.com/oL8o8dh.png): dark screen and an error about WS - `WebSocket connection to 'ws://localhost:8989/!/socket' failed: Connection closed before receiving a handshake response`

Do I miss something in my set up? I've tried to integrate it with my other application but I cannot really get the demo to work.

**Comment by silverwind** [comment]
This example was pretty outdated, I think it was written before droppy was using websockets. I updated it and adjusted the module API to expose the `setupWebSocket` method.

I'm not totally happy with this, but it seems there's no way around to exposing the http server so the websocket module(s) can work.

Also, I'm pretty sure it will not play nicely with other websockets on the same server. In that case, I'd suggest running droppy standalone and using a reverse proxy instead.

Will relase 8.0.0 with these changes shortly.
