### ISSUE TITLE
arm64 / v8 Docker Image ?

### ISSUE THREAD

**Issue by thomas-gt** [silverwind/droppy#339]
I noticed Docker images are available for arm v6 and v7.
Is it possible to provide arm64 / v8 too ?
Thanks.

**Comment by silverwind** [comment]
Try this image: https://hub.docker.com/r/silverwind/arm64v8-droppy/

(I don't have any armv8 hardware to test on)

**Comment by thomas-gt** [comment]
Sounds good. 1st test shows image is working fine.
Thanks !
