### ISSUE TITLE
BlackScreen after the auth

### ISSUE THREAD

**Issue by studioai** [silverwind/droppy#340]
When I try to access droppy via my ddns domain. It shows me an auth dialog. After I input my ID/Pass, It only shows a black screen.

my config is below
```
{
  "listeners": [
    {
      "host": [
        "0.0.0.0",
        "::"
      ],
      "port": 80,
      "protocol": "http"
    }
  ],
  "public": false,
  "timestamps": true,
  "linkLength": 5,
  "logLevel": 0,
  "maxFileSize": 0,
  "updateInterval": 1000,
  "pollingInterval": 0,
  "keepAlive": 20000,
  "allowFrame": false,
  "readOnly": false,
  "compression": false,
  "ignorePatterns": [
    "!!"
  ],
  "watch": true
}

```

and .service

```
[Unit]
Description=droppy
After=network.target

[Service]
ExecStart=/usr/local/bin/droppy start -f /mnt/usb_1
Environment="NODE_ENV=production"
AmbientCapabilities=CAP_NET_BIND_SERVICE
Restart=always
User=root
Group=root
SyslogIdentifier=droppy
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
```

Did I do something wrong?

**Comment by silverwind** [comment]
Any errors visible in the browser console?

**Comment by studioai** [comment]
> Any errors visible in the browser console?

No error, just black screen. however, I can access to droppy via private IP (192.168.x.x) adress without a problem.

**Comment by studioai** [comment]
maybe related to #248?

**Comment by studioai** [comment]
I found a web socket error, Do I need to set a reverse proxy?
I know there’s configuration examples for nginx and Apache. but I’m running a lighttpd. Is there an example for it?

**Comment by studioai** [comment]
OK, I'll try to change my web server to nginx. So, let me close this issue.

**Comment by silverwind** [comment]
I meant you should try another browser :)

**Comment by studioai** [comment]
Sorry, I forgot to say that I've tried iOS safari and the result was the same. So I'll try nginx server.
