### ISSUE TITLE
do you plan to use "react" to instead of jquery ?

### ISSUE THREAD

**Issue by zxydaisy** [silverwind/droppy#342]
i think your project is good.
but if we use jquery, we need to write more code, do you plan to import react ?

**Comment by silverwind** [comment]
I would like to, but it'd be a huge rewrite and I don't think I have the time or motivation to do so right now.

**Comment by sardaukar** [comment]
@zxydaisy the project seems to work fine without React 🤷‍♂️

**Comment by silverwind** [comment]
Yeah not gonna do this anytime soon. If I wrote it from scratch today, sure I would use React 😉.
