### ISSUE TITLE
Getting SyntaxError: Unexpected token * when attempting to start droppy

### ISSUE THREAD

**Issue by Sil3ntPr0digy** [silverwind/droppy#355]
I spooled up a fresh CentOS 7 vm, installed epel-release, nodejs, and droppy, however when attempting to start up droppy I am receiving the follow error:

![droppy](https://user-images.githubusercontent.com/2136965/45259100-51a43000-b3b4-11e8-8563-15b94c8979a6.PNG)

Please advise. Thanks for your time.

**Comment by Sil3ntPr0digy** [comment]
An update, I have tested, and removing one of the '*' does resolve the error and allow the program to start without issue.

**Comment by silverwind** [comment]
You need to upgrade to Node.js 7.5.0 or higher for the exponential operator. I realize the current Node.js 6.0 requirement is not accurate currently.

**Comment by silverwind** [comment]
You can install `droppy@9.1.5` which is the last version working on Node.js 6.0.0. I'll publish `10.0.0` shortly, which will require Node.js 8.0.0 or greater.
