### ISSUE TITLE
Play pause on audio not working

### ISSUE THREAD

**Issue by pradyvr** [silverwind/droppy#356]
The issue is in 
client/client.js file:2279

      if (icon[0].className == "play") {

the fixed code will be like this.

      if (icon[0].className.baseVal == "play") {

The problem is that  pause play svg icon element use baseval attribute to get the string .(animated SVG)

I would like to contribute to this project. Can anyone guide me to the steps to go through? Thank you.

**Comment by silverwind** [comment]
Let's do a slightly different fix:

````diff
diff --git a/client/client.js b/client/client.js
index 9389dc10..d68f9ac3 100644
--- a/client/client.js
+++ b/client/client.js
@@ -2275,9 +2275,9 @@
     });
     bar.find(".pause-play").off("click").on("click", function(event) {
       var icon   = $(this).children("svg");
       var player = $(this).parents(".audio-bar").find(".audio-player")[0];
-      if (icon[0].className === "play") {
+      if (icon[0].getAttribute("class") === "play") {
         icon.replaceWith($(svg("pause")));
         player.play();
       } else {
         icon.replaceWith($(svg("play")));
````

> I would like to contribute to this project. Can anyone guide me to the steps to go through? Thank you.

You can follow a guide like [this one](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github) to create a pull request.

**Comment by silverwind** [comment]
Thanks for https://github.com/silverwind/droppy/commit/592397517eb39d128860c379f6266e9f4b397668.
