### ISSUE TITLE
Anyone tried using this with Traefik?

### ISSUE THREAD

**Issue by wshayes** [silverwind/droppy#361]
First off - this is a great, simple, very slick webfile manager - thank you!

Trying to get this to work with Traefik.  I tried the traefik labels below which should have made it available via https://webfiles.xxx.biodati.com. I can access it fine via http://xxx.biodati.com:8989 (IP locked - I can set it up on an open server if needed).  I'm getting a gateway timeout - though I do see the front and backend's showing up in the Traefik dashboard for droppy.  I also see an entry in the access.log for traefik, but I don't see anything in the droppy docker logs.  I'm not sure if this is a Traefik issue or droppy, but I have several other services that work great using the same setup.

    # Web file manager
    droppy:
      container_name: droppy
      image: silverwind/droppy
      ports:
        - 8989:8989
      volumes:
        - ./webfiles/config:/config
        - ./webfiles/files:/files
      # labels:
      #   - traefik.enable=true
      #   - traefik.backend=droppy
      #   - traefik.frontend.rule=Host:webfiles.${BS_HOST_NAME:?err}
      #   - traefik.port=8989
      restart: unless-stopped

**Comment by silverwind** [comment]
Never tried it, but I don't see why it should not work, it's a standard HTTP 1.1 service. Just make sure that websocket traffic is forwarded correctly, as this is often an issue with reverse proxies (Thought this does not explain your current issue).
