### ISSUE TITLE
Cyrillic font is ugly

### ISSUE THREAD

**Issue by sprnza** [silverwind/droppy#364]
Is there a way to configure font is being used? I've got some files and folders named in Cyrillyc and the look is not unified.
![default](https://user-images.githubusercontent.com/1968839/49020561-ce6bcc80-f1a1-11e8-8af4-63384646cff3.png)

**Comment by silverwind** [comment]
Afraid not, but I'm open to suggestions for a lightweight and free font that includes such glyphs, ideally available on Google fonts.

**Comment by sprnza** [comment]
A[ lot of them ](https://fonts.google.com/?subset=cyrillic)supports Cyrrillic

**Comment by sprnza** [comment]
Yep, everything is cool now! Thank you for so quick fixes!
