### ISSUE TITLE
ignorePatterns usage is unclear

### ISSUE THREAD

**Issue by hagfelsh** [silverwind/droppy#366]
This is more of a me-problem, I suspect, but I can't figure out how to ignore a directory.

The ignorePatterns states that it's an array of file globs.  I'd like to ignore a hidden directory in the /files dir called .secret_stuff.

No variation of this has worked so far.. which one didn't I try?
`javascript
"ignorePatterns": [".secret_stuff/"],
`

**Comment by silverwind** [comment]
It's not you, seems a recent refactoring made the option dysfunctional. Fixed.

**Comment by joedefen** [comment]
Is this ignorePatterns broken again?  I cannot exclude any directory no matter what syntax I use.  If not this, is there a way to including a list if directories?
