### ISSUE TITLE
Apache Reverse proxy with Docker

### ISSUE THREAD

**Issue by gerroon** [silverwind/droppy#369]
Hi

Can you please tell me how I can use the Docker install with Apache? 

The docker install works great and I put this in my Apache site but all I get is an empty page

```
ProxyPass /droppy http://127.0.0.1:8989
ProxyPassReverse /droppy http://127.0.0.1:8989
``` 

thanks

**Comment by silverwind** [comment]
There is a wiki page for Apache configuration. No idea if there are any specifics about Apache in Docker, but it should get you started:

https://github.com/silverwind/droppy/wiki/Apache-reverse-proxy

**Comment by silverwind** [comment]
I personally prefer to run the web server outside of Docker for ease of configuration, but it is certainly an option to have it containerized too. There is a official Apache image: https://hub.docker.com/_/httpd.

**Comment by whalehub** [comment]
@gerroon No offense, but nobody should be using Apache anymore. It's the only webserver that's vulnerable to the devastating Slowloris DoS attack, for one. If you're working with containers, I'd recommend using either Traefik or Caddy as your reverse proxy.

**Comment by silverwind** [comment]
Closing, nothing to do here.
