### ISSUE TITLE
Filenames with an asterisk get "Invalid file path:" error

### ISSUE THREAD

**Issue by zoof** [silverwind/droppy#372]
I know it is not usual to have a file name with a wildcard character but it does seem that it should be a case to allow for.

**Comment by zoof** [comment]
To elaborate just a tiny bit, this error happens when attempting to upload a file with an asterisk in its name.

**Comment by zoof** [comment]
Never mind.  This appears to be related to #331.

**Comment by silverwind** [comment]
Yes, `*` is a forbidden character on Windows file systems which would make the file non-portable so I chose to forbid these characters everywhere.
