### ISSUE TITLE
Server responded with HTTP 500 on uploading file

### ISSUE THREAD

**Issue by andrew-medvedev** [silverwind/droppy#374]
When I'm trying to upload a file I get 500 response: https://gyazo.com/575c0eab182e3df80830ad15d8d46f67

But I can freely create files(like file **created** created 49 secs ago)

Here details of request: https://gyazo.com/8e9925afe948f6ac4648cd71cff0038a

And versions: https://gyazo.com/788106cc4ec0cc4ddff73177ae339000

What to do?

**Comment by silverwind** [comment]
Can you show the relevant entries in the server log? Also would recommend to update to the latest version.

**Comment by andrew-medvedev** [comment]
There are no error logs if you about them: https://gyazo.com/059e9ca8d51c9f1e8b26c6c5e9292e4c

**Comment by andrew-medvedev** [comment]
Same problem after installing version 11.0.4

**Comment by andrew-medvedev** [comment]
It's something with nginx. Retreat

**Comment by andrew-medvedev** [comment]
No, it's not nginx. Interesting thing: if I put droppy on 0.0.0.0 - everything will be fine, but fail on 127.0.0.0 through nginx. But at the same time nginx shows no erros. Here is log: 
[access.log](https://github.com/silverwind/droppy/files/3072554/access.log)

**Comment by silverwind** [comment]
The requests come in as `/droppy/!/upload?vId=0&to=%2F&rename=0` in nginx but come in as `/!/upload` to droppy without a query string so are rejected by the application. Anything in your nginx config that could modify/cut off those query strings?

**Comment by andrew-medvedev** [comment]
Yes. A piece of config like this: https://gyazo.com/2982bce2ac2604036786b7624ba590d8

I made it bc I want droppy to be on `/droppy` path. But I don't know the way how to make droppy to listen for this path

**Comment by silverwind** [comment]
That rewrite is probably breaking it. Try

````
location /droppy/ {
  proxy_pass http://droppy/;
}
````

**Comment by andrew-medvedev** [comment]
Nope. Unsatisfactory result: https://gyazo.com/f1198db618331a917b22dc9a3f9a8689

**Comment by silverwind** [comment]
No idea where your 403 comes from, but such a server block works for me. Not that trailing slashes are significant.

````nginx
  server {
    listen 443 ssl http2;
    location /droppy/ {
      proxy_pass http://droppy/;
    }
  }
````

**Comment by andrew-medvedev** [comment]
Sad

**Comment by andrew-medvedev** [comment]
okay now
