### ISSUE TITLE
caddy reverse proxy

### ISSUE THREAD

**Issue by fallenczar** [silverwind/droppy#383]
Caddy is a HTTP/2 web server with automatic HTTPS that is gaining popularity due to ease of use and its built in security features. here is my `Caddyfile` to reverse proxy droppy

```
droppy.your.domain {
proxy / 127.0.0.1:8989 {        
    websocket      
    transparent
    }
timeouts none
}
```

**Comment by silverwind** [comment]
Added as an example, thanks.
