### ISSUE TITLE
Multiarch Docker image

### ISSUE THREAD

**Issue by ncresswell** [silverwind/droppy#404]
Hi, any plans for a multi-arch docker image that supports both AMD64 and ARM64? 

I am using silverwind/arm64v8-droppy, but it would be good if the main image was multi-arch instead so can be sure of using the latest version at all times.

**Comment by silverwind** [comment]
Done in https://github.com/silverwind/droppy/commit/b20ed87ed115d6fbddde80f4767a221cba878dc3.
