### ISSUE TITLE
Add read-only mode with no authentication 

### ISSUE THREAD

**Issue by NightMachinary** [silverwind/droppy#414]

**Comment by pmow** [comment]
Wouldn't that just be public=true and read-only=true?

**Comment by ashleysommer** [comment]
Can we reopen this?
I think a more suitable description of the feature request would be:
Can we have a public mode where if the user is not logged in, they can still access the files, but they are read-only, but also there is the option to log in, then when you are authenticated you have write permission.

Correct me if I'm wrong, but I'm pretty sure public=true and read-only=true doesn't do that?
