### ISSUE TITLE
docker image last update a year ago

### ISSUE THREAD

**Issue by AkgunFatih** [silverwind/droppy#420]
like the title says
the docker image hosted here https://hub.docker.com/r/silverwind/droppy
is a year old

pls consider updating it

**Comment by ashleysommer** [comment]
@AkgunFatih 
See here: https://github.com/silverwind/droppy/releases
The latest version released of Droppy is v11.1.0, released June 28 2019. It is the same version that is on Dockerhub.

With no release since then, why does the docker image need to be updated?
