### ISSUE TITLE
Truncate path elements when necessary

### ISSUE THREAD

**Issue by ZombieHippie** [silverwind/droppy#64]
![image](https://f.cloud.github.com/assets/2925395/2303323/aa8cc0fe-a1b4-11e3-976b-8c490d399047.png)
If a directory name is longer than what can fit in the path, we should show at least the last couple letters of the parenting folder's name

**Comment by silverwind** [comment]
Pure CSS to the rescue, I think it's working nicely.

![](https://cloud.githubusercontent.com/assets/115237/20029705/4068a1bc-a354-11e6-975c-fbd197b612b7.png)
