### ISSUE TITLE
Folder actions children of view directory

### ISSUE THREAD

**Issue by colelawrence** [silverwind/droppy#88]
Folder actions are specific to directory views so a directory view should have these actions in a toolbar of some sort:
- New File
- New Folder
- Upload Files
- Upload Folder
- Paste Item

It would also be nice to have consistent view action locations across different view types.
For example:
![toolbar-1](https://f.cloud.github.com/assets/2925395/2388329/a1e771d6-a940-11e3-9b44-a8316c412d5a.gif)
![toolbar-2](https://f.cloud.github.com/assets/2925395/2388331/a343dc04-a940-11e3-89cf-0abd4d3bf25e.gif)
- Save Document
- Toggle bulb
- Toggle Line wrapping
- Use Tabs/Spaces
- Indent Unit

**Comment by silverwind** [comment]
Fixed in https://github.com/silverwind/droppy/commit/67e75c6e40db31128f8e8108f5ac969ea25e3fe9 et al.
